//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Runtime.CompilerServices;
using Unity.IL2CPP.CompilerServices;

#pragma warning disable 0660, 0661

namespace CGTK.Utilities.BetterMath
{
    /// <summary>A 2x3 matrix of bools.</summary>
    [System.Serializable]
    [Il2CppEagerStaticClassConstruction]
    public partial struct Boolx2x3 : System.IEquatable<Boolx2x3>
    {
        /// <summary>Column 0 of the matrix.</summary>
        public Boolx2 c0;
        /// <summary>Column 1 of the matrix.</summary>
        public Boolx2 c1;
        /// <summary>Column 2 of the matrix.</summary>
        public Boolx2 c2;


        /// <summary>Constructs a Boolx2x3 matrix from three Boolx2 vectors.</summary>
        /// <param name="c0">The matrix column c0 will be set to this value.</param>
        /// <param name="c1">The matrix column c1 will be set to this value.</param>
        /// <param name="c2">The matrix column c2 will be set to this value.</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Boolx2x3(Boolx2 c0, Boolx2 c1, Boolx2 c2)
        {
            this.c0 = c0;
            this.c1 = c1;
            this.c2 = c2;
        }

        /// <summary>Constructs a Boolx2x3 matrix from 6 bool values given in row-major order.</summary>
        /// <param name="m00">The matrix at row 0, column 0 will be set to this value.</param>
        /// <param name="m01">The matrix at row 0, column 1 will be set to this value.</param>
        /// <param name="m02">The matrix at row 0, column 2 will be set to this value.</param>
        /// <param name="m10">The matrix at row 1, column 0 will be set to this value.</param>
        /// <param name="m11">The matrix at row 1, column 1 will be set to this value.</param>
        /// <param name="m12">The matrix at row 1, column 2 will be set to this value.</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Boolx2x3(bool m00, bool m01, bool m02,
                       bool m10, bool m11, bool m12)
        {
            this.c0 = new Boolx2(m00, m10);
            this.c1 = new Boolx2(m01, m11);
            this.c2 = new Boolx2(m02, m12);
        }

        /// <summary>Constructs a Boolx2x3 matrix from a single bool value by assigning it to every component.</summary>
        /// <param name="v">bool to convert to Boolx2x3</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Boolx2x3(bool v)
        {
            this.c0 = v;
            this.c1 = v;
            this.c2 = v;
        }


        /// <summary>Implicitly converts a single bool value to a Boolx2x3 matrix by assigning it to every component.</summary>
        /// <param name="v">bool to convert to Boolx2x3</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator Boolx2x3(bool v) { return new Boolx2x3(v); }


        /// <summary>Returns the result of a componentwise equality operation on two Boolx2x3 matrices.</summary>
        /// <param name="lhs">Left hand side Boolx2x3 to use to compute componentwise equality.</param>
        /// <param name="rhs">Right hand side Boolx2x3 to use to compute componentwise equality.</param>
        /// <returns>Boolx2x3 result of the componentwise equality.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Boolx2x3 operator == (Boolx2x3 lhs, Boolx2x3 rhs) { return new Boolx2x3 (lhs.c0 == rhs.c0, lhs.c1 == rhs.c1, lhs.c2 == rhs.c2); }

        /// <summary>Returns the result of a componentwise equality operation on a Boolx2x3 matrix and a bool value.</summary>
        /// <param name="lhs">Left hand side Boolx2x3 to use to compute componentwise equality.</param>
        /// <param name="rhs">Right hand side bool to use to compute componentwise equality.</param>
        /// <returns>Boolx2x3 result of the componentwise equality.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Boolx2x3 operator == (Boolx2x3 lhs, bool rhs) { return new Boolx2x3 (lhs.c0 == rhs, lhs.c1 == rhs, lhs.c2 == rhs); }

        /// <summary>Returns the result of a componentwise equality operation on a bool value and a Boolx2x3 matrix.</summary>
        /// <param name="lhs">Left hand side bool to use to compute componentwise equality.</param>
        /// <param name="rhs">Right hand side Boolx2x3 to use to compute componentwise equality.</param>
        /// <returns>Boolx2x3 result of the componentwise equality.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Boolx2x3 operator == (bool lhs, Boolx2x3 rhs) { return new Boolx2x3 (lhs == rhs.c0, lhs == rhs.c1, lhs == rhs.c2); }


        /// <summary>Returns the result of a componentwise not equal operation on two Boolx2x3 matrices.</summary>
        /// <param name="lhs">Left hand side Boolx2x3 to use to compute componentwise not equal.</param>
        /// <param name="rhs">Right hand side Boolx2x3 to use to compute componentwise not equal.</param>
        /// <returns>Boolx2x3 result of the componentwise not equal.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Boolx2x3 operator != (Boolx2x3 lhs, Boolx2x3 rhs) { return new Boolx2x3 (lhs.c0 != rhs.c0, lhs.c1 != rhs.c1, lhs.c2 != rhs.c2); }

        /// <summary>Returns the result of a componentwise not equal operation on a Boolx2x3 matrix and a bool value.</summary>
        /// <param name="lhs">Left hand side Boolx2x3 to use to compute componentwise not equal.</param>
        /// <param name="rhs">Right hand side bool to use to compute componentwise not equal.</param>
        /// <returns>Boolx2x3 result of the componentwise not equal.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Boolx2x3 operator != (Boolx2x3 lhs, bool rhs) { return new Boolx2x3 (lhs.c0 != rhs, lhs.c1 != rhs, lhs.c2 != rhs); }

        /// <summary>Returns the result of a componentwise not equal operation on a bool value and a Boolx2x3 matrix.</summary>
        /// <param name="lhs">Left hand side bool to use to compute componentwise not equal.</param>
        /// <param name="rhs">Right hand side Boolx2x3 to use to compute componentwise not equal.</param>
        /// <returns>Boolx2x3 result of the componentwise not equal.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Boolx2x3 operator != (bool lhs, Boolx2x3 rhs) { return new Boolx2x3 (lhs != rhs.c0, lhs != rhs.c1, lhs != rhs.c2); }


        /// <summary>Returns the result of a componentwise not operation on a Boolx2x3 matrix.</summary>
        /// <param name="val">Value to use when computing the componentwise not.</param>
        /// <returns>Boolx2x3 result of the componentwise not.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Boolx2x3 operator ! (Boolx2x3 val) { return new Boolx2x3 (!val.c0, !val.c1, !val.c2); }


        /// <summary>Returns the result of a componentwise bitwise and operation on two Boolx2x3 matrices.</summary>
        /// <param name="lhs">Left hand side Boolx2x3 to use to compute componentwise bitwise and.</param>
        /// <param name="rhs">Right hand side Boolx2x3 to use to compute componentwise bitwise and.</param>
        /// <returns>Boolx2x3 result of the componentwise bitwise and.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Boolx2x3 operator & (Boolx2x3 lhs, Boolx2x3 rhs) { return new Boolx2x3 (lhs.c0 & rhs.c0, lhs.c1 & rhs.c1, lhs.c2 & rhs.c2); }

        /// <summary>Returns the result of a componentwise bitwise and operation on a Boolx2x3 matrix and a bool value.</summary>
        /// <param name="lhs">Left hand side Boolx2x3 to use to compute componentwise bitwise and.</param>
        /// <param name="rhs">Right hand side bool to use to compute componentwise bitwise and.</param>
        /// <returns>Boolx2x3 result of the componentwise bitwise and.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Boolx2x3 operator & (Boolx2x3 lhs, bool rhs) { return new Boolx2x3 (lhs.c0 & rhs, lhs.c1 & rhs, lhs.c2 & rhs); }

        /// <summary>Returns the result of a componentwise bitwise and operation on a bool value and a Boolx2x3 matrix.</summary>
        /// <param name="lhs">Left hand side bool to use to compute componentwise bitwise and.</param>
        /// <param name="rhs">Right hand side Boolx2x3 to use to compute componentwise bitwise and.</param>
        /// <returns>Boolx2x3 result of the componentwise bitwise and.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Boolx2x3 operator & (bool lhs, Boolx2x3 rhs) { return new Boolx2x3 (lhs & rhs.c0, lhs & rhs.c1, lhs & rhs.c2); }


        /// <summary>Returns the result of a componentwise bitwise or operation on two Boolx2x3 matrices.</summary>
        /// <param name="lhs">Left hand side Boolx2x3 to use to compute componentwise bitwise or.</param>
        /// <param name="rhs">Right hand side Boolx2x3 to use to compute componentwise bitwise or.</param>
        /// <returns>Boolx2x3 result of the componentwise bitwise or.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Boolx2x3 operator | (Boolx2x3 lhs, Boolx2x3 rhs) { return new Boolx2x3 (lhs.c0 | rhs.c0, lhs.c1 | rhs.c1, lhs.c2 | rhs.c2); }

        /// <summary>Returns the result of a componentwise bitwise or operation on a Boolx2x3 matrix and a bool value.</summary>
        /// <param name="lhs">Left hand side Boolx2x3 to use to compute componentwise bitwise or.</param>
        /// <param name="rhs">Right hand side bool to use to compute componentwise bitwise or.</param>
        /// <returns>Boolx2x3 result of the componentwise bitwise or.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Boolx2x3 operator | (Boolx2x3 lhs, bool rhs) { return new Boolx2x3 (lhs.c0 | rhs, lhs.c1 | rhs, lhs.c2 | rhs); }

        /// <summary>Returns the result of a componentwise bitwise or operation on a bool value and a Boolx2x3 matrix.</summary>
        /// <param name="lhs">Left hand side bool to use to compute componentwise bitwise or.</param>
        /// <param name="rhs">Right hand side Boolx2x3 to use to compute componentwise bitwise or.</param>
        /// <returns>Boolx2x3 result of the componentwise bitwise or.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Boolx2x3 operator | (bool lhs, Boolx2x3 rhs) { return new Boolx2x3 (lhs | rhs.c0, lhs | rhs.c1, lhs | rhs.c2); }


        /// <summary>Returns the result of a componentwise bitwise exclusive or operation on two Boolx2x3 matrices.</summary>
        /// <param name="lhs">Left hand side Boolx2x3 to use to compute componentwise bitwise exclusive or.</param>
        /// <param name="rhs">Right hand side Boolx2x3 to use to compute componentwise bitwise exclusive or.</param>
        /// <returns>Boolx2x3 result of the componentwise bitwise exclusive or.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Boolx2x3 operator ^ (Boolx2x3 lhs, Boolx2x3 rhs) { return new Boolx2x3 (lhs.c0 ^ rhs.c0, lhs.c1 ^ rhs.c1, lhs.c2 ^ rhs.c2); }

        /// <summary>Returns the result of a componentwise bitwise exclusive or operation on a Boolx2x3 matrix and a bool value.</summary>
        /// <param name="lhs">Left hand side Boolx2x3 to use to compute componentwise bitwise exclusive or.</param>
        /// <param name="rhs">Right hand side bool to use to compute componentwise bitwise exclusive or.</param>
        /// <returns>Boolx2x3 result of the componentwise bitwise exclusive or.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Boolx2x3 operator ^ (Boolx2x3 lhs, bool rhs) { return new Boolx2x3 (lhs.c0 ^ rhs, lhs.c1 ^ rhs, lhs.c2 ^ rhs); }

        /// <summary>Returns the result of a componentwise bitwise exclusive or operation on a bool value and a Boolx2x3 matrix.</summary>
        /// <param name="lhs">Left hand side bool to use to compute componentwise bitwise exclusive or.</param>
        /// <param name="rhs">Right hand side Boolx2x3 to use to compute componentwise bitwise exclusive or.</param>
        /// <returns>Boolx2x3 result of the componentwise bitwise exclusive or.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Boolx2x3 operator ^ (bool lhs, Boolx2x3 rhs) { return new Boolx2x3 (lhs ^ rhs.c0, lhs ^ rhs.c1, lhs ^ rhs.c2); }



        /// <summary>Returns the Boolx2 element at a specified index.</summary>
        unsafe public ref Boolx2 this[int index]
        {
            get
            {
#if ENABLE_UNITY_COLLECTIONS_CHECKS
                if ((uint)index >= 3)
                    throw new System.ArgumentException("index must be between[0...2]");
#endif
                fixed (Boolx2x3* array = &this) { return ref ((Boolx2*)array)[index]; }
            }
        }

        /// <summary>Returns true if the Boolx2x3 is equal to a given Boolx2x3, false otherwise.</summary>
        /// <param name="rhs">Right hand side argument to compare equality with.</param>
        /// <returns>The result of the equality comparison.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public bool Equals(Boolx2x3 rhs) { return c0.Equals(rhs.c0) && c1.Equals(rhs.c1) && c2.Equals(rhs.c2); }

        /// <summary>Returns true if the Boolx2x3 is equal to a given Boolx2x3, false otherwise.</summary>
        /// <param name="o">Right hand side argument to compare equality with.</param>
        /// <returns>The result of the equality comparison.</returns>
        public override bool Equals(object o) { return o is Boolx2x3 converted && Equals(converted); }


        /// <summary>Returns a hash code for the Boolx2x3.</summary>
        /// <returns>The computed hash code.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public override int GetHashCode() { return (int)Maths.hash(this); }


        /// <summary>Returns a string representation of the Boolx2x3.</summary>
        /// <returns>String representation of the value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public override string ToString()
        {
            return string.Format("Boolx2x3({0}, {1}, {2},  {3}, {4}, {5})", c0.x, c1.x, c2.x, c0.y, c1.y, c2.y);
        }

    }

    public static partial class Maths
    {
        /*
        /// <summary>Returns a Boolx2x3 matrix constructed from three Boolx2 vectors.</summary>
        /// <param name="c0">The matrix column c0 will be set to this value.</param>
        /// <param name="c1">The matrix column c1 will be set to this value.</param>
        /// <param name="c2">The matrix column c2 will be set to this value.</param>
        /// <returns>Boolx2x3 constructed from arguments.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Boolx2x3 bool2x3(Boolx2 c0, Boolx2 c1, Boolx2 c2) { return new Boolx2x3(c0, c1, c2); }

        /// <summary>Returns a Boolx2x3 matrix constructed from from 6 bool values given in row-major order.</summary>
        /// <param name="m00">The matrix at row 0, column 0 will be set to this value.</param>
        /// <param name="m01">The matrix at row 0, column 1 will be set to this value.</param>
        /// <param name="m02">The matrix at row 0, column 2 will be set to this value.</param>
        /// <param name="m10">The matrix at row 1, column 0 will be set to this value.</param>
        /// <param name="m11">The matrix at row 1, column 1 will be set to this value.</param>
        /// <param name="m12">The matrix at row 1, column 2 will be set to this value.</param>
        /// <returns>Boolx2x3 constructed from arguments.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Boolx2x3 bool2x3(bool m00, bool m01, bool m02,
                                      bool m10, bool m11, bool m12)
        {
            return new Boolx2x3(m00, m01, m02,
                               m10, m11, m12);
        }

        /// <summary>Returns a Boolx2x3 matrix constructed from a single bool value by assigning it to every component.</summary>
        /// <param name="v">bool to convert to Boolx2x3</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Boolx2x3 bool2x3(bool v) { return new Boolx2x3(v); }
        */

        /// <summary>Return the Boolx3x2 transpose of a Boolx2x3 matrix.</summary>
        /// <param name="v">Value to transpose.</param>
        /// <returns>Transposed value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Boolx3x2 transpose(Boolx2x3 v)
        {
            return new Boolx3x2(
                v.c0.x, v.c0.y,
                v.c1.x, v.c1.y,
                v.c2.x, v.c2.y);
        }

        /// <summary>Returns a uint hash code of a Boolx2x3 matrix.</summary>
        /// <param name="v">Matrix value to hash.</param>
        /// <returns>uint hash of the argument.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static uint hash(Boolx2x3 v)
        {
            return csum(x:
                select(new U32x2(0x7BE39F3Bu, 0xFAB9913Fu), new U32x2(0xB4501269u, 0xE04B89FDu), v.c0) +
                select(new U32x2(0xDB3DE101u, 0x7B6D1B4Bu), new U32x2(0x58399E77u, 0x5EAC29C9u), v.c1) +
                select(new U32x2(0xFC6014F9u, 0x6BF6693Fu), new U32x2(0x9D1B1D9Bu, 0xF842F5C1u), v.c2));
        }

        /// <summary>
        /// Returns a U32x2 vector hash code of a Boolx2x3 matrix.
        /// When multiple elements are to be hashes together, it can more efficient to calculate and combine wide hash
        /// that are only reduced to a narrow uint hash at the very end instead of at every step.
        /// </summary>
        /// <param name="v">Matrix value to hash.</param>
        /// <returns>U32x2 hash of the argument.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2 hashwide(Boolx2x3 v)
        {
            return (select(new U32x2(0xA47EC335u, 0xA477DF57u), new U32x2(0xC4B1493Fu, 0xBA0966D3u), v.c0) +
                    select(new U32x2(0xAFBEE253u, 0x5B419C01u), new U32x2(0x515D90F5u, 0xEC9F68F3u), v.c1) +
                    select(new U32x2(0xF9EA92D5u, 0xC2FAFCB9u), new U32x2(0x616E9CA1u, 0xC5C5394Bu), v.c2));
        }

    }
}
