//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Runtime.CompilerServices;
using Unity.IL2CPP.CompilerServices;

#pragma warning disable 0660, 0661

namespace CGTK.Utilities.BetterMath
{
    /// <summary>A 3x4 matrix of doubles.</summary>
    [System.Serializable]
    [Il2CppEagerStaticClassConstruction]
    public partial struct F64x3x4 : System.IEquatable<F64x3x4>, IFormattable
    {
        /// <summary>Column 0 of the matrix.</summary>
        public F64x3 c0;
        /// <summary>Column 1 of the matrix.</summary>
        public F64x3 c1;
        /// <summary>Column 2 of the matrix.</summary>
        public F64x3 c2;
        /// <summary>Column 3 of the matrix.</summary>
        public F64x3 c3;

        /// <summary>F64x3x4 zero value.</summary>
        public static readonly F64x3x4 zero;

        /// <summary>Constructs a F64x3x4 matrix from four F64x3 vectors.</summary>
        /// <param name="c0">The matrix column c0 will be set to this value.</param>
        /// <param name="c1">The matrix column c1 will be set to this value.</param>
        /// <param name="c2">The matrix column c2 will be set to this value.</param>
        /// <param name="c3">The matrix column c3 will be set to this value.</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public F64x3x4(F64x3 c0, F64x3 c1, F64x3 c2, F64x3 c3)
        {
            this.c0 = c0;
            this.c1 = c1;
            this.c2 = c2;
            this.c3 = c3;
        }

        /// <summary>Constructs a F64x3x4 matrix from 12 double values given in row-major order.</summary>
        /// <param name="m00">The matrix at row 0, column 0 will be set to this value.</param>
        /// <param name="m01">The matrix at row 0, column 1 will be set to this value.</param>
        /// <param name="m02">The matrix at row 0, column 2 will be set to this value.</param>
        /// <param name="m03">The matrix at row 0, column 3 will be set to this value.</param>
        /// <param name="m10">The matrix at row 1, column 0 will be set to this value.</param>
        /// <param name="m11">The matrix at row 1, column 1 will be set to this value.</param>
        /// <param name="m12">The matrix at row 1, column 2 will be set to this value.</param>
        /// <param name="m13">The matrix at row 1, column 3 will be set to this value.</param>
        /// <param name="m20">The matrix at row 2, column 0 will be set to this value.</param>
        /// <param name="m21">The matrix at row 2, column 1 will be set to this value.</param>
        /// <param name="m22">The matrix at row 2, column 2 will be set to this value.</param>
        /// <param name="m23">The matrix at row 2, column 3 will be set to this value.</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public F64x3x4(double m00, double m01, double m02, double m03,
                         double m10, double m11, double m12, double m13,
                         double m20, double m21, double m22, double m23)
        {
            this.c0 = new F64x3(m00, m10, m20);
            this.c1 = new F64x3(m01, m11, m21);
            this.c2 = new F64x3(m02, m12, m22);
            this.c3 = new F64x3(m03, m13, m23);
        }

        /// <summary>Constructs a F64x3x4 matrix from a single double value by assigning it to every component.</summary>
        /// <param name="v">double to convert to F64x3x4</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public F64x3x4(double v)
        {
            this.c0 = v;
            this.c1 = v;
            this.c2 = v;
            this.c3 = v;
        }

        /// <summary>Constructs a F64x3x4 matrix from a single bool value by converting it to double and assigning it to every component.</summary>
        /// <param name="v">bool to convert to F64x3x4</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public F64x3x4(bool v)
        {
            this.c0 = Maths.select(new F64x3(0.0), new F64x3(1.0), v);
            this.c1 = Maths.select(new F64x3(0.0), new F64x3(1.0), v);
            this.c2 = Maths.select(new F64x3(0.0), new F64x3(1.0), v);
            this.c3 = Maths.select(new F64x3(0.0), new F64x3(1.0), v);
        }

        /// <summary>Constructs a F64x3x4 matrix from a Boolx3x4 matrix by componentwise conversion.</summary>
        /// <param name="v">Boolx3x4 to convert to F64x3x4</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public F64x3x4(Boolx3x4 v)
        {
            this.c0 = Maths.select(new F64x3(0.0), new F64x3(1.0), v.c0);
            this.c1 = Maths.select(new F64x3(0.0), new F64x3(1.0), v.c1);
            this.c2 = Maths.select(new F64x3(0.0), new F64x3(1.0), v.c2);
            this.c3 = Maths.select(new F64x3(0.0), new F64x3(1.0), v.c3);
        }

        /// <summary>Constructs a F64x3x4 matrix from a single int value by converting it to double and assigning it to every component.</summary>
        /// <param name="v">int to convert to F64x3x4</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public F64x3x4(int v)
        {
            this.c0 = v;
            this.c1 = v;
            this.c2 = v;
            this.c3 = v;
        }

        /// <summary>Constructs a F64x3x4 matrix from a I32x3x4 matrix by componentwise conversion.</summary>
        /// <param name="v">I32x3x4 to convert to F64x3x4</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public F64x3x4(I32x3x4 v)
        {
            this.c0 = v.c0;
            this.c1 = v.c1;
            this.c2 = v.c2;
            this.c3 = v.c3;
        }

        /// <summary>Constructs a F64x3x4 matrix from a single uint value by converting it to double and assigning it to every component.</summary>
        /// <param name="v">uint to convert to F64x3x4</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public F64x3x4(uint v)
        {
            this.c0 = v;
            this.c1 = v;
            this.c2 = v;
            this.c3 = v;
        }

        /// <summary>Constructs a F64x3x4 matrix from a U32x3x4 matrix by componentwise conversion.</summary>
        /// <param name="v">U32x3x4 to convert to F64x3x4</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public F64x3x4(U32x3x4 v)
        {
            this.c0 = v.c0;
            this.c1 = v.c1;
            this.c2 = v.c2;
            this.c3 = v.c3;
        }

        /// <summary>Constructs a F64x3x4 matrix from a single float value by converting it to double and assigning it to every component.</summary>
        /// <param name="v">float to convert to F64x3x4</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public F64x3x4(float v)
        {
            this.c0 = v;
            this.c1 = v;
            this.c2 = v;
            this.c3 = v;
        }

        /// <summary>Constructs a F64x3x4 matrix from a F32x3x4 matrix by componentwise conversion.</summary>
        /// <param name="v">F32x3x4 to convert to F64x3x4</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public F64x3x4(F32x3x4 v)
        {
            this.c0 = v.c0;
            this.c1 = v.c1;
            this.c2 = v.c2;
            this.c3 = v.c3;
        }


        /// <summary>Implicitly converts a single double value to a F64x3x4 matrix by assigning it to every component.</summary>
        /// <param name="v">double to convert to F64x3x4</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator F64x3x4(double v) { return new F64x3x4(v); }

        /// <summary>Explicitly converts a single bool value to a F64x3x4 matrix by converting it to double and assigning it to every component.</summary>
        /// <param name="v">bool to convert to F64x3x4</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static explicit operator F64x3x4(bool v) { return new F64x3x4(v); }

        /// <summary>Explicitly converts a Boolx3x4 matrix to a F64x3x4 matrix by componentwise conversion.</summary>
        /// <param name="v">Boolx3x4 to convert to F64x3x4</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static explicit operator F64x3x4(Boolx3x4 v) { return new F64x3x4(v); }

        /// <summary>Implicitly converts a single int value to a F64x3x4 matrix by converting it to double and assigning it to every component.</summary>
        /// <param name="v">int to convert to F64x3x4</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator F64x3x4(int v) { return new F64x3x4(v); }

        /// <summary>Implicitly converts a I32x3x4 matrix to a F64x3x4 matrix by componentwise conversion.</summary>
        /// <param name="v">I32x3x4 to convert to F64x3x4</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator F64x3x4(I32x3x4 v) { return new F64x3x4(v); }

        /// <summary>Implicitly converts a single uint value to a F64x3x4 matrix by converting it to double and assigning it to every component.</summary>
        /// <param name="v">uint to convert to F64x3x4</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator F64x3x4(uint v) { return new F64x3x4(v); }

        /// <summary>Implicitly converts a U32x3x4 matrix to a F64x3x4 matrix by componentwise conversion.</summary>
        /// <param name="v">U32x3x4 to convert to F64x3x4</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator F64x3x4(U32x3x4 v) { return new F64x3x4(v); }

        /// <summary>Implicitly converts a single float value to a F64x3x4 matrix by converting it to double and assigning it to every component.</summary>
        /// <param name="v">float to convert to F64x3x4</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator F64x3x4(float v) { return new F64x3x4(v); }

        /// <summary>Implicitly converts a F32x3x4 matrix to a F64x3x4 matrix by componentwise conversion.</summary>
        /// <param name="v">F32x3x4 to convert to F64x3x4</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator F64x3x4(F32x3x4 v) { return new F64x3x4(v); }


        /// <summary>Returns the result of a componentwise multiplication operation on two F64x3x4 matrices.</summary>
        /// <param name="lhs">Left hand side F64x3x4 to use to compute componentwise multiplication.</param>
        /// <param name="rhs">Right hand side F64x3x4 to use to compute componentwise multiplication.</param>
        /// <returns>F64x3x4 result of the componentwise multiplication.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static F64x3x4 operator * (F64x3x4 lhs, F64x3x4 rhs) { return new F64x3x4 (lhs.c0 * rhs.c0, lhs.c1 * rhs.c1, lhs.c2 * rhs.c2, lhs.c3 * rhs.c3); }

        /// <summary>Returns the result of a componentwise multiplication operation on a F64x3x4 matrix and a double value.</summary>
        /// <param name="lhs">Left hand side F64x3x4 to use to compute componentwise multiplication.</param>
        /// <param name="rhs">Right hand side double to use to compute componentwise multiplication.</param>
        /// <returns>F64x3x4 result of the componentwise multiplication.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static F64x3x4 operator * (F64x3x4 lhs, double rhs) { return new F64x3x4 (lhs.c0 * rhs, lhs.c1 * rhs, lhs.c2 * rhs, lhs.c3 * rhs); }

        /// <summary>Returns the result of a componentwise multiplication operation on a double value and a F64x3x4 matrix.</summary>
        /// <param name="lhs">Left hand side double to use to compute componentwise multiplication.</param>
        /// <param name="rhs">Right hand side F64x3x4 to use to compute componentwise multiplication.</param>
        /// <returns>F64x3x4 result of the componentwise multiplication.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static F64x3x4 operator * (double lhs, F64x3x4 rhs) { return new F64x3x4 (lhs * rhs.c0, lhs * rhs.c1, lhs * rhs.c2, lhs * rhs.c3); }


        /// <summary>Returns the result of a componentwise addition operation on two F64x3x4 matrices.</summary>
        /// <param name="lhs">Left hand side F64x3x4 to use to compute componentwise addition.</param>
        /// <param name="rhs">Right hand side F64x3x4 to use to compute componentwise addition.</param>
        /// <returns>F64x3x4 result of the componentwise addition.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static F64x3x4 operator + (F64x3x4 lhs, F64x3x4 rhs) { return new F64x3x4 (lhs.c0 + rhs.c0, lhs.c1 + rhs.c1, lhs.c2 + rhs.c2, lhs.c3 + rhs.c3); }

        /// <summary>Returns the result of a componentwise addition operation on a F64x3x4 matrix and a double value.</summary>
        /// <param name="lhs">Left hand side F64x3x4 to use to compute componentwise addition.</param>
        /// <param name="rhs">Right hand side double to use to compute componentwise addition.</param>
        /// <returns>F64x3x4 result of the componentwise addition.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static F64x3x4 operator + (F64x3x4 lhs, double rhs) { return new F64x3x4 (lhs.c0 + rhs, lhs.c1 + rhs, lhs.c2 + rhs, lhs.c3 + rhs); }

        /// <summary>Returns the result of a componentwise addition operation on a double value and a F64x3x4 matrix.</summary>
        /// <param name="lhs">Left hand side double to use to compute componentwise addition.</param>
        /// <param name="rhs">Right hand side F64x3x4 to use to compute componentwise addition.</param>
        /// <returns>F64x3x4 result of the componentwise addition.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static F64x3x4 operator + (double lhs, F64x3x4 rhs) { return new F64x3x4 (lhs + rhs.c0, lhs + rhs.c1, lhs + rhs.c2, lhs + rhs.c3); }


        /// <summary>Returns the result of a componentwise subtraction operation on two F64x3x4 matrices.</summary>
        /// <param name="lhs">Left hand side F64x3x4 to use to compute componentwise subtraction.</param>
        /// <param name="rhs">Right hand side F64x3x4 to use to compute componentwise subtraction.</param>
        /// <returns>F64x3x4 result of the componentwise subtraction.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static F64x3x4 operator - (F64x3x4 lhs, F64x3x4 rhs) { return new F64x3x4 (lhs.c0 - rhs.c0, lhs.c1 - rhs.c1, lhs.c2 - rhs.c2, lhs.c3 - rhs.c3); }

        /// <summary>Returns the result of a componentwise subtraction operation on a F64x3x4 matrix and a double value.</summary>
        /// <param name="lhs">Left hand side F64x3x4 to use to compute componentwise subtraction.</param>
        /// <param name="rhs">Right hand side double to use to compute componentwise subtraction.</param>
        /// <returns>F64x3x4 result of the componentwise subtraction.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static F64x3x4 operator - (F64x3x4 lhs, double rhs) { return new F64x3x4 (lhs.c0 - rhs, lhs.c1 - rhs, lhs.c2 - rhs, lhs.c3 - rhs); }

        /// <summary>Returns the result of a componentwise subtraction operation on a double value and a F64x3x4 matrix.</summary>
        /// <param name="lhs">Left hand side double to use to compute componentwise subtraction.</param>
        /// <param name="rhs">Right hand side F64x3x4 to use to compute componentwise subtraction.</param>
        /// <returns>F64x3x4 result of the componentwise subtraction.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static F64x3x4 operator - (double lhs, F64x3x4 rhs) { return new F64x3x4 (lhs - rhs.c0, lhs - rhs.c1, lhs - rhs.c2, lhs - rhs.c3); }


        /// <summary>Returns the result of a componentwise division operation on two F64x3x4 matrices.</summary>
        /// <param name="lhs">Left hand side F64x3x4 to use to compute componentwise division.</param>
        /// <param name="rhs">Right hand side F64x3x4 to use to compute componentwise division.</param>
        /// <returns>F64x3x4 result of the componentwise division.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static F64x3x4 operator / (F64x3x4 lhs, F64x3x4 rhs) { return new F64x3x4 (lhs.c0 / rhs.c0, lhs.c1 / rhs.c1, lhs.c2 / rhs.c2, lhs.c3 / rhs.c3); }

        /// <summary>Returns the result of a componentwise division operation on a F64x3x4 matrix and a double value.</summary>
        /// <param name="lhs">Left hand side F64x3x4 to use to compute componentwise division.</param>
        /// <param name="rhs">Right hand side double to use to compute componentwise division.</param>
        /// <returns>F64x3x4 result of the componentwise division.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static F64x3x4 operator / (F64x3x4 lhs, double rhs) { return new F64x3x4 (lhs.c0 / rhs, lhs.c1 / rhs, lhs.c2 / rhs, lhs.c3 / rhs); }

        /// <summary>Returns the result of a componentwise division operation on a double value and a F64x3x4 matrix.</summary>
        /// <param name="lhs">Left hand side double to use to compute componentwise division.</param>
        /// <param name="rhs">Right hand side F64x3x4 to use to compute componentwise division.</param>
        /// <returns>F64x3x4 result of the componentwise division.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static F64x3x4 operator / (double lhs, F64x3x4 rhs) { return new F64x3x4 (lhs / rhs.c0, lhs / rhs.c1, lhs / rhs.c2, lhs / rhs.c3); }


        /// <summary>Returns the result of a componentwise modulus operation on two F64x3x4 matrices.</summary>
        /// <param name="lhs">Left hand side F64x3x4 to use to compute componentwise modulus.</param>
        /// <param name="rhs">Right hand side F64x3x4 to use to compute componentwise modulus.</param>
        /// <returns>F64x3x4 result of the componentwise modulus.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static F64x3x4 operator % (F64x3x4 lhs, F64x3x4 rhs) { return new F64x3x4 (lhs.c0 % rhs.c0, lhs.c1 % rhs.c1, lhs.c2 % rhs.c2, lhs.c3 % rhs.c3); }

        /// <summary>Returns the result of a componentwise modulus operation on a F64x3x4 matrix and a double value.</summary>
        /// <param name="lhs">Left hand side F64x3x4 to use to compute componentwise modulus.</param>
        /// <param name="rhs">Right hand side double to use to compute componentwise modulus.</param>
        /// <returns>F64x3x4 result of the componentwise modulus.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static F64x3x4 operator % (F64x3x4 lhs, double rhs) { return new F64x3x4 (lhs.c0 % rhs, lhs.c1 % rhs, lhs.c2 % rhs, lhs.c3 % rhs); }

        /// <summary>Returns the result of a componentwise modulus operation on a double value and a F64x3x4 matrix.</summary>
        /// <param name="lhs">Left hand side double to use to compute componentwise modulus.</param>
        /// <param name="rhs">Right hand side F64x3x4 to use to compute componentwise modulus.</param>
        /// <returns>F64x3x4 result of the componentwise modulus.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static F64x3x4 operator % (double lhs, F64x3x4 rhs) { return new F64x3x4 (lhs % rhs.c0, lhs % rhs.c1, lhs % rhs.c2, lhs % rhs.c3); }


        /// <summary>Returns the result of a componentwise increment operation on a F64x3x4 matrix.</summary>
        /// <param name="val">Value to use when computing the componentwise increment.</param>
        /// <returns>F64x3x4 result of the componentwise increment.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static F64x3x4 operator ++ (F64x3x4 val) { return new F64x3x4 (++val.c0, ++val.c1, ++val.c2, ++val.c3); }


        /// <summary>Returns the result of a componentwise decrement operation on a F64x3x4 matrix.</summary>
        /// <param name="val">Value to use when computing the componentwise decrement.</param>
        /// <returns>F64x3x4 result of the componentwise decrement.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static F64x3x4 operator -- (F64x3x4 val) { return new F64x3x4 (--val.c0, --val.c1, --val.c2, --val.c3); }


        /// <summary>Returns the result of a componentwise less than operation on two F64x3x4 matrices.</summary>
        /// <param name="lhs">Left hand side F64x3x4 to use to compute componentwise less than.</param>
        /// <param name="rhs">Right hand side F64x3x4 to use to compute componentwise less than.</param>
        /// <returns>Boolx3x4 result of the componentwise less than.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Boolx3x4 operator < (F64x3x4 lhs, F64x3x4 rhs) { return new Boolx3x4 (lhs.c0 < rhs.c0, lhs.c1 < rhs.c1, lhs.c2 < rhs.c2, lhs.c3 < rhs.c3); }

        /// <summary>Returns the result of a componentwise less than operation on a F64x3x4 matrix and a double value.</summary>
        /// <param name="lhs">Left hand side F64x3x4 to use to compute componentwise less than.</param>
        /// <param name="rhs">Right hand side double to use to compute componentwise less than.</param>
        /// <returns>Boolx3x4 result of the componentwise less than.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Boolx3x4 operator < (F64x3x4 lhs, double rhs) { return new Boolx3x4 (lhs.c0 < rhs, lhs.c1 < rhs, lhs.c2 < rhs, lhs.c3 < rhs); }

        /// <summary>Returns the result of a componentwise less than operation on a double value and a F64x3x4 matrix.</summary>
        /// <param name="lhs">Left hand side double to use to compute componentwise less than.</param>
        /// <param name="rhs">Right hand side F64x3x4 to use to compute componentwise less than.</param>
        /// <returns>Boolx3x4 result of the componentwise less than.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Boolx3x4 operator < (double lhs, F64x3x4 rhs) { return new Boolx3x4 (lhs < rhs.c0, lhs < rhs.c1, lhs < rhs.c2, lhs < rhs.c3); }


        /// <summary>Returns the result of a componentwise less or equal operation on two F64x3x4 matrices.</summary>
        /// <param name="lhs">Left hand side F64x3x4 to use to compute componentwise less or equal.</param>
        /// <param name="rhs">Right hand side F64x3x4 to use to compute componentwise less or equal.</param>
        /// <returns>Boolx3x4 result of the componentwise less or equal.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Boolx3x4 operator <= (F64x3x4 lhs, F64x3x4 rhs) { return new Boolx3x4 (lhs.c0 <= rhs.c0, lhs.c1 <= rhs.c1, lhs.c2 <= rhs.c2, lhs.c3 <= rhs.c3); }

        /// <summary>Returns the result of a componentwise less or equal operation on a F64x3x4 matrix and a double value.</summary>
        /// <param name="lhs">Left hand side F64x3x4 to use to compute componentwise less or equal.</param>
        /// <param name="rhs">Right hand side double to use to compute componentwise less or equal.</param>
        /// <returns>Boolx3x4 result of the componentwise less or equal.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Boolx3x4 operator <= (F64x3x4 lhs, double rhs) { return new Boolx3x4 (lhs.c0 <= rhs, lhs.c1 <= rhs, lhs.c2 <= rhs, lhs.c3 <= rhs); }

        /// <summary>Returns the result of a componentwise less or equal operation on a double value and a F64x3x4 matrix.</summary>
        /// <param name="lhs">Left hand side double to use to compute componentwise less or equal.</param>
        /// <param name="rhs">Right hand side F64x3x4 to use to compute componentwise less or equal.</param>
        /// <returns>Boolx3x4 result of the componentwise less or equal.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Boolx3x4 operator <= (double lhs, F64x3x4 rhs) { return new Boolx3x4 (lhs <= rhs.c0, lhs <= rhs.c1, lhs <= rhs.c2, lhs <= rhs.c3); }


        /// <summary>Returns the result of a componentwise greater than operation on two F64x3x4 matrices.</summary>
        /// <param name="lhs">Left hand side F64x3x4 to use to compute componentwise greater than.</param>
        /// <param name="rhs">Right hand side F64x3x4 to use to compute componentwise greater than.</param>
        /// <returns>Boolx3x4 result of the componentwise greater than.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Boolx3x4 operator > (F64x3x4 lhs, F64x3x4 rhs) { return new Boolx3x4 (lhs.c0 > rhs.c0, lhs.c1 > rhs.c1, lhs.c2 > rhs.c2, lhs.c3 > rhs.c3); }

        /// <summary>Returns the result of a componentwise greater than operation on a F64x3x4 matrix and a double value.</summary>
        /// <param name="lhs">Left hand side F64x3x4 to use to compute componentwise greater than.</param>
        /// <param name="rhs">Right hand side double to use to compute componentwise greater than.</param>
        /// <returns>Boolx3x4 result of the componentwise greater than.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Boolx3x4 operator > (F64x3x4 lhs, double rhs) { return new Boolx3x4 (lhs.c0 > rhs, lhs.c1 > rhs, lhs.c2 > rhs, lhs.c3 > rhs); }

        /// <summary>Returns the result of a componentwise greater than operation on a double value and a F64x3x4 matrix.</summary>
        /// <param name="lhs">Left hand side double to use to compute componentwise greater than.</param>
        /// <param name="rhs">Right hand side F64x3x4 to use to compute componentwise greater than.</param>
        /// <returns>Boolx3x4 result of the componentwise greater than.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Boolx3x4 operator > (double lhs, F64x3x4 rhs) { return new Boolx3x4 (lhs > rhs.c0, lhs > rhs.c1, lhs > rhs.c2, lhs > rhs.c3); }


        /// <summary>Returns the result of a componentwise greater or equal operation on two F64x3x4 matrices.</summary>
        /// <param name="lhs">Left hand side F64x3x4 to use to compute componentwise greater or equal.</param>
        /// <param name="rhs">Right hand side F64x3x4 to use to compute componentwise greater or equal.</param>
        /// <returns>Boolx3x4 result of the componentwise greater or equal.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Boolx3x4 operator >= (F64x3x4 lhs, F64x3x4 rhs) { return new Boolx3x4 (lhs.c0 >= rhs.c0, lhs.c1 >= rhs.c1, lhs.c2 >= rhs.c2, lhs.c3 >= rhs.c3); }

        /// <summary>Returns the result of a componentwise greater or equal operation on a F64x3x4 matrix and a double value.</summary>
        /// <param name="lhs">Left hand side F64x3x4 to use to compute componentwise greater or equal.</param>
        /// <param name="rhs">Right hand side double to use to compute componentwise greater or equal.</param>
        /// <returns>Boolx3x4 result of the componentwise greater or equal.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Boolx3x4 operator >= (F64x3x4 lhs, double rhs) { return new Boolx3x4 (lhs.c0 >= rhs, lhs.c1 >= rhs, lhs.c2 >= rhs, lhs.c3 >= rhs); }

        /// <summary>Returns the result of a componentwise greater or equal operation on a double value and a F64x3x4 matrix.</summary>
        /// <param name="lhs">Left hand side double to use to compute componentwise greater or equal.</param>
        /// <param name="rhs">Right hand side F64x3x4 to use to compute componentwise greater or equal.</param>
        /// <returns>Boolx3x4 result of the componentwise greater or equal.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Boolx3x4 operator >= (double lhs, F64x3x4 rhs) { return new Boolx3x4 (lhs >= rhs.c0, lhs >= rhs.c1, lhs >= rhs.c2, lhs >= rhs.c3); }


        /// <summary>Returns the result of a componentwise unary minus operation on a F64x3x4 matrix.</summary>
        /// <param name="val">Value to use when computing the componentwise unary minus.</param>
        /// <returns>F64x3x4 result of the componentwise unary minus.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static F64x3x4 operator - (F64x3x4 val) { return new F64x3x4 (-val.c0, -val.c1, -val.c2, -val.c3); }


        /// <summary>Returns the result of a componentwise unary plus operation on a F64x3x4 matrix.</summary>
        /// <param name="val">Value to use when computing the componentwise unary plus.</param>
        /// <returns>F64x3x4 result of the componentwise unary plus.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static F64x3x4 operator + (F64x3x4 val) { return new F64x3x4 (+val.c0, +val.c1, +val.c2, +val.c3); }


        /// <summary>Returns the result of a componentwise equality operation on two F64x3x4 matrices.</summary>
        /// <param name="lhs">Left hand side F64x3x4 to use to compute componentwise equality.</param>
        /// <param name="rhs">Right hand side F64x3x4 to use to compute componentwise equality.</param>
        /// <returns>Boolx3x4 result of the componentwise equality.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Boolx3x4 operator == (F64x3x4 lhs, F64x3x4 rhs) { return new Boolx3x4 (lhs.c0 == rhs.c0, lhs.c1 == rhs.c1, lhs.c2 == rhs.c2, lhs.c3 == rhs.c3); }

        /// <summary>Returns the result of a componentwise equality operation on a F64x3x4 matrix and a double value.</summary>
        /// <param name="lhs">Left hand side F64x3x4 to use to compute componentwise equality.</param>
        /// <param name="rhs">Right hand side double to use to compute componentwise equality.</param>
        /// <returns>Boolx3x4 result of the componentwise equality.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Boolx3x4 operator == (F64x3x4 lhs, double rhs) { return new Boolx3x4 (lhs.c0 == rhs, lhs.c1 == rhs, lhs.c2 == rhs, lhs.c3 == rhs); }

        /// <summary>Returns the result of a componentwise equality operation on a double value and a F64x3x4 matrix.</summary>
        /// <param name="lhs">Left hand side double to use to compute componentwise equality.</param>
        /// <param name="rhs">Right hand side F64x3x4 to use to compute componentwise equality.</param>
        /// <returns>Boolx3x4 result of the componentwise equality.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Boolx3x4 operator == (double lhs, F64x3x4 rhs) { return new Boolx3x4 (lhs == rhs.c0, lhs == rhs.c1, lhs == rhs.c2, lhs == rhs.c3); }


        /// <summary>Returns the result of a componentwise not equal operation on two F64x3x4 matrices.</summary>
        /// <param name="lhs">Left hand side F64x3x4 to use to compute componentwise not equal.</param>
        /// <param name="rhs">Right hand side F64x3x4 to use to compute componentwise not equal.</param>
        /// <returns>Boolx3x4 result of the componentwise not equal.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Boolx3x4 operator != (F64x3x4 lhs, F64x3x4 rhs) { return new Boolx3x4 (lhs.c0 != rhs.c0, lhs.c1 != rhs.c1, lhs.c2 != rhs.c2, lhs.c3 != rhs.c3); }

        /// <summary>Returns the result of a componentwise not equal operation on a F64x3x4 matrix and a double value.</summary>
        /// <param name="lhs">Left hand side F64x3x4 to use to compute componentwise not equal.</param>
        /// <param name="rhs">Right hand side double to use to compute componentwise not equal.</param>
        /// <returns>Boolx3x4 result of the componentwise not equal.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Boolx3x4 operator != (F64x3x4 lhs, double rhs) { return new Boolx3x4 (lhs.c0 != rhs, lhs.c1 != rhs, lhs.c2 != rhs, lhs.c3 != rhs); }

        /// <summary>Returns the result of a componentwise not equal operation on a double value and a F64x3x4 matrix.</summary>
        /// <param name="lhs">Left hand side double to use to compute componentwise not equal.</param>
        /// <param name="rhs">Right hand side F64x3x4 to use to compute componentwise not equal.</param>
        /// <returns>Boolx3x4 result of the componentwise not equal.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Boolx3x4 operator != (double lhs, F64x3x4 rhs) { return new Boolx3x4 (lhs != rhs.c0, lhs != rhs.c1, lhs != rhs.c2, lhs != rhs.c3); }



        /// <summary>Returns the F64x3 element at a specified index.</summary>
        unsafe public ref F64x3 this[int index]
        {
            get
            {
#if ENABLE_UNITY_COLLECTIONS_CHECKS
                if ((uint)index >= 4)
                    throw new System.ArgumentException("index must be between[0...3]");
#endif
                fixed (F64x3x4* array = &this) { return ref ((F64x3*)array)[index]; }
            }
        }

        /// <summary>Returns true if the F64x3x4 is equal to a given F64x3x4, false otherwise.</summary>
        /// <param name="rhs">Right hand side argument to compare equality with.</param>
        /// <returns>The result of the equality comparison.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public bool Equals(F64x3x4 rhs) { return c0.Equals(rhs.c0) && c1.Equals(rhs.c1) && c2.Equals(rhs.c2) && c3.Equals(rhs.c3); }

        /// <summary>Returns true if the F64x3x4 is equal to a given F64x3x4, false otherwise.</summary>
        /// <param name="o">Right hand side argument to compare equality with.</param>
        /// <returns>The result of the equality comparison.</returns>
        public override bool Equals(object o) { return o is F64x3x4 converted && Equals(converted); }


        /// <summary>Returns a hash code for the F64x3x4.</summary>
        /// <returns>The computed hash code.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public override int GetHashCode() { return (int)Maths.hash(this); }


        /// <summary>Returns a string representation of the F64x3x4.</summary>
        /// <returns>String representation of the value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public override string ToString()
        {
            return string.Format("F64x3x4({0}, {1}, {2}, {3},  {4}, {5}, {6}, {7},  {8}, {9}, {10}, {11})", c0.x, c1.x, c2.x, c3.x, c0.y, c1.y, c2.y, c3.y, c0.z, c1.z, c2.z, c3.z);
        }

        /// <summary>Returns a string representation of the F64x3x4 using a specified format and culture-specific format information.</summary>
        /// <param name="format">Format string to use during string formatting.</param>
        /// <param name="formatProvider">Format provider to use during string formatting.</param>
        /// <returns>String representation of the value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public string ToString(string format, IFormatProvider formatProvider)
        {
            return string.Format("F64x3x4({0}, {1}, {2}, {3},  {4}, {5}, {6}, {7},  {8}, {9}, {10}, {11})", c0.x.ToString(format, formatProvider), c1.x.ToString(format, formatProvider), c2.x.ToString(format, formatProvider), c3.x.ToString(format, formatProvider), c0.y.ToString(format, formatProvider), c1.y.ToString(format, formatProvider), c2.y.ToString(format, formatProvider), c3.y.ToString(format, formatProvider), c0.z.ToString(format, formatProvider), c1.z.ToString(format, formatProvider), c2.z.ToString(format, formatProvider), c3.z.ToString(format, formatProvider));
        }

    }

    public static partial class Maths
    {
        /*
        /// <summary>Returns a F64x3x4 matrix constructed from four F64x3 vectors.</summary>
        /// <param name="c0">The matrix column c0 will be set to this value.</param>
        /// <param name="c1">The matrix column c1 will be set to this value.</param>
        /// <param name="c2">The matrix column c2 will be set to this value.</param>
        /// <param name="c3">The matrix column c3 will be set to this value.</param>
        /// <returns>F64x3x4 constructed from arguments.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static F64x3x4 F64x3x4(F64x3 c0, F64x3 c1, F64x3 c2, F64x3 c3) { return new F64x3x4(c0, c1, c2, c3); }

        /// <summary>Returns a F64x3x4 matrix constructed from from 12 double values given in row-major order.</summary>
        /// <param name="m00">The matrix at row 0, column 0 will be set to this value.</param>
        /// <param name="m01">The matrix at row 0, column 1 will be set to this value.</param>
        /// <param name="m02">The matrix at row 0, column 2 will be set to this value.</param>
        /// <param name="m03">The matrix at row 0, column 3 will be set to this value.</param>
        /// <param name="m10">The matrix at row 1, column 0 will be set to this value.</param>
        /// <param name="m11">The matrix at row 1, column 1 will be set to this value.</param>
        /// <param name="m12">The matrix at row 1, column 2 will be set to this value.</param>
        /// <param name="m13">The matrix at row 1, column 3 will be set to this value.</param>
        /// <param name="m20">The matrix at row 2, column 0 will be set to this value.</param>
        /// <param name="m21">The matrix at row 2, column 1 will be set to this value.</param>
        /// <param name="m22">The matrix at row 2, column 2 will be set to this value.</param>
        /// <param name="m23">The matrix at row 2, column 3 will be set to this value.</param>
        /// <returns>F64x3x4 constructed from arguments.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static F64x3x4 F64x3x4(double m00, double m01, double m02, double m03,
                                          double m10, double m11, double m12, double m13,
                                          double m20, double m21, double m22, double m23)
        {
            return new F64x3x4(m00, m01, m02, m03,
                                 m10, m11, m12, m13,
                                 m20, m21, m22, m23);
        }

        /// <summary>Returns a F64x3x4 matrix constructed from a single double value by assigning it to every component.</summary>
        /// <param name="v">double to convert to F64x3x4</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static F64x3x4 F64x3x4(double v) { return new F64x3x4(v); }

        /// <summary>Returns a F64x3x4 matrix constructed from a single bool value by converting it to double and assigning it to every component.</summary>
        /// <param name="v">bool to convert to F64x3x4</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static F64x3x4 F64x3x4(bool v) { return new F64x3x4(v); }

        /// <summary>Return a F64x3x4 matrix constructed from a Boolx3x4 matrix by componentwise conversion.</summary>
        /// <param name="v">Boolx3x4 to convert to F64x3x4</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static F64x3x4 F64x3x4(Boolx3x4 v) { return new F64x3x4(v); }

        /// <summary>Returns a F64x3x4 matrix constructed from a single int value by converting it to double and assigning it to every component.</summary>
        /// <param name="v">int to convert to F64x3x4</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static F64x3x4 F64x3x4(int v) { return new F64x3x4(v); }

        /// <summary>Return a F64x3x4 matrix constructed from a I32x3x4 matrix by componentwise conversion.</summary>
        /// <param name="v">I32x3x4 to convert to F64x3x4</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static F64x3x4 F64x3x4(I32x3x4 v) { return new F64x3x4(v); }

        /// <summary>Returns a F64x3x4 matrix constructed from a single uint value by converting it to double and assigning it to every component.</summary>
        /// <param name="v">uint to convert to F64x3x4</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static F64x3x4 F64x3x4(uint v) { return new F64x3x4(v); }

        /// <summary>Return a F64x3x4 matrix constructed from a U32x3x4 matrix by componentwise conversion.</summary>
        /// <param name="v">U32x3x4 to convert to F64x3x4</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static F64x3x4 F64x3x4(U32x3x4 v) { return new F64x3x4(v); }

        /// <summary>Returns a F64x3x4 matrix constructed from a single float value by converting it to double and assigning it to every component.</summary>
        /// <param name="v">float to convert to F64x3x4</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static F64x3x4 F64x3x4(float v) { return new F64x3x4(v); }

        /// <summary>Return a F64x3x4 matrix constructed from a F32x3x4 matrix by componentwise conversion.</summary>
        /// <param name="v">F32x3x4 to convert to F64x3x4</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static F64x3x4 F64x3x4(F32x3x4 v) { return new F64x3x4(v); }
        */

        /// <summary>Return the F64x4x3 transpose of a F64x3x4 matrix.</summary>
        /// <param name="v">Value to transpose.</param>
        /// <returns>Transposed value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static F64x4x3 transpose(F64x3x4 v)
        {
            return new F64x4x3(
                v.c0.x, v.c0.y, v.c0.z,
                v.c1.x, v.c1.y, v.c1.z,
                v.c2.x, v.c2.y, v.c2.z,
                v.c3.x, v.c3.y, v.c3.z);
        }

        /// <summary>Fast matrix inverse for rigid transforms (orthonormal basis and translation)</summary>
        /// <param name="m">Matrix to invert.</param>
        /// <returns>The inverted matrix.</returns>
        public static F64x3x4 fastinverse(F64x3x4 m)
        {
            F64x3 c0 = m.c0;
            F64x3 c1 = m.c1;
            F64x3 c2 = m.c2;
            F64x3 pos = m.c3;

            F64x3 r0 = new F64x3(c0.x, c1.x, c2.x);
            F64x3 r1 = new F64x3(c0.y, c1.y, c2.y);
            F64x3 r2 = new F64x3(c0.z, c1.z, c2.z);

            pos = -(r0 * pos.x + r1 * pos.y + r2 * pos.z);

            return new F64x3x4(r0, r1, r2, pos);
        }

        /// <summary>Returns a uint hash code of a F64x3x4 matrix.</summary>
        /// <param name="v">Matrix value to hash.</param>
        /// <returns>uint hash of the argument.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static uint hash(F64x3x4 v)
        {
            return csum(x:
                FoldToU32(v.c0) * new U32x3(0xEE390C97u, 0x9C8A2F05u, 0x4DDC6509u) +
                FoldToU32(v.c1) * new U32x3(0x7CF083CBu, 0x5C4D6CEDu, 0xF9137117u) +
                FoldToU32(v.c2) * new U32x3(0xE857DCE1u, 0xF62213C5u, 0x9CDAA959u) +
                FoldToU32(v.c3) * new U32x3(0xAA269ABFu, 0xD54BA36Fu, 0xFD0847B9u)) + 0x8189A683u;
        }

        /// <summary>
        /// Returns a U32x3 vector hash code of a F64x3x4 matrix.
        /// When multiple elements are to be hashes together, it can more efficient to calculate and combine wide hash
        /// that are only reduced to a narrow uint hash at the very end instead of at every step.
        /// </summary>
        /// <param name="v">Matrix value to hash.</param>
        /// <returns>U32x3 hash of the argument.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x3 hashwide(F64x3x4 v)
        {
            return (FoldToU32(v.c0) * new U32x3(0xB139D651u, 0xE7579997u, 0xEF7D56C7u) +
                    FoldToU32(v.c1) * new U32x3(0x66F38F0Bu, 0x624256A3u, 0x5292ADE1u) +
                    FoldToU32(v.c2) * new U32x3(0xD2E590E5u, 0xF25BE857u, 0x9BC17CE7u) +
                    FoldToU32(v.c3) * new U32x3(0xC8B86851u, 0x64095221u, 0xADF428FFu)) + 0xA3977109u;
        }

    }
}
