//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Runtime.CompilerServices;
using System.Diagnostics;
using Unity.IL2CPP.CompilerServices;

#pragma warning disable 0660, 0661

namespace CGTK.Utilities.BetterMath
{
    /// <summary>A 2 component vector of uints.</summary>
    [DebuggerTypeProxy(typeof(U32x2.DebuggerProxy))]
    [System.Serializable]
    [Il2CppEagerStaticClassConstruction]
    public partial struct U32x2 : System.IEquatable<U32x2>, IFormattable
    {
        /// <summary>x component of the vector.</summary>
        public uint x;
        /// <summary>y component of the vector.</summary>
        public uint y;

        /// <summary>U32x2 zero value.</summary>
        public static readonly U32x2 zero;

        /// <summary>Constructs a U32x2 vector from two uint values.</summary>
        /// <param name="x">The constructed vector's x component will be set to this value.</param>
        /// <param name="y">The constructed vector's y component will be set to this value.</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public U32x2(uint x, uint y)
        {
            this.x = x;
            this.y = y;
        }

        /// <summary>Constructs a U32x2 vector from a U32x2 vector.</summary>
        /// <param name="xy">The constructed vector's xy components will be set to this value.</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public U32x2(U32x2 xy)
        {
            this.x = xy.x;
            this.y = xy.y;
        }

        /// <summary>Constructs a U32x2 vector from a single uint value by assigning it to every component.</summary>
        /// <param name="v">uint to convert to U32x2</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public U32x2(uint v)
        {
            this.x = v;
            this.y = v;
        }

        /// <summary>Constructs a U32x2 vector from a single bool value by converting it to uint and assigning it to every component.</summary>
        /// <param name="v">bool to convert to U32x2</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public U32x2(bool v)
        {
            this.x = v ? 1u : 0u;
            this.y = v ? 1u : 0u;
        }

        /// <summary>Constructs a U32x2 vector from a Boolx2 vector by componentwise conversion.</summary>
        /// <param name="v">Boolx2 to convert to U32x2</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public U32x2(Boolx2 v)
        {
            this.x = v.x ? 1u : 0u;
            this.y = v.y ? 1u : 0u;
        }

        /// <summary>Constructs a U32x2 vector from a single int value by converting it to uint and assigning it to every component.</summary>
        /// <param name="v">int to convert to U32x2</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public U32x2(int v)
        {
            this.x = (uint)v;
            this.y = (uint)v;
        }

        /// <summary>Constructs a U32x2 vector from a I32x2 vector by componentwise conversion.</summary>
        /// <param name="v">I32x2 to convert to U32x2</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public U32x2(I32x2 v)
        {
            this.x = (uint)v.x;
            this.y = (uint)v.y;
        }

        /// <summary>Constructs a U32x2 vector from a single float value by converting it to uint and assigning it to every component.</summary>
        /// <param name="v">float to convert to U32x2</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public U32x2(float v)
        {
            this.x = (uint)v;
            this.y = (uint)v;
        }

        /// <summary>Constructs a U32x2 vector from a F32x2 vector by componentwise conversion.</summary>
        /// <param name="v">F32x2 to convert to U32x2</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public U32x2(F32x2 v)
        {
            this.x = (uint)v.x;
            this.y = (uint)v.y;
        }

        /// <summary>Constructs a U32x2 vector from a single double value by converting it to uint and assigning it to every component.</summary>
        /// <param name="v">double to convert to U32x2</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public U32x2(double v)
        {
            this.x = (uint)v;
            this.y = (uint)v;
        }

        /// <summary>Constructs a U32x2 vector from a F64x2 vector by componentwise conversion.</summary>
        /// <param name="v">F64x2 to convert to U32x2</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public U32x2(F64x2 v)
        {
            this.x = (uint)v.x;
            this.y = (uint)v.y;
        }


        /// <summary>Implicitly converts a single uint value to a U32x2 vector by assigning it to every component.</summary>
        /// <param name="v">uint to convert to U32x2</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator U32x2(uint v) { return new U32x2(v); }

        /// <summary>Explicitly converts a single bool value to a U32x2 vector by converting it to uint and assigning it to every component.</summary>
        /// <param name="v">bool to convert to U32x2</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static explicit operator U32x2(bool v) { return new U32x2(v); }

        /// <summary>Explicitly converts a Boolx2 vector to a U32x2 vector by componentwise conversion.</summary>
        /// <param name="v">Boolx2 to convert to U32x2</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static explicit operator U32x2(Boolx2 v) { return new U32x2(v); }

        /// <summary>Explicitly converts a single int value to a U32x2 vector by converting it to uint and assigning it to every component.</summary>
        /// <param name="v">int to convert to U32x2</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static explicit operator U32x2(int v) { return new U32x2(v); }

        /// <summary>Explicitly converts a I32x2 vector to a U32x2 vector by componentwise conversion.</summary>
        /// <param name="v">I32x2 to convert to U32x2</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static explicit operator U32x2(I32x2 v) { return new U32x2(v); }

        /// <summary>Explicitly converts a single float value to a U32x2 vector by converting it to uint and assigning it to every component.</summary>
        /// <param name="v">float to convert to U32x2</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static explicit operator U32x2(float v) { return new U32x2(v); }

        /// <summary>Explicitly converts a F32x2 vector to a U32x2 vector by componentwise conversion.</summary>
        /// <param name="v">F32x2 to convert to U32x2</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static explicit operator U32x2(F32x2 v) { return new U32x2(v); }

        /// <summary>Explicitly converts a single double value to a U32x2 vector by converting it to uint and assigning it to every component.</summary>
        /// <param name="v">double to convert to U32x2</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static explicit operator U32x2(double v) { return new U32x2(v); }

        /// <summary>Explicitly converts a F64x2 vector to a U32x2 vector by componentwise conversion.</summary>
        /// <param name="v">F64x2 to convert to U32x2</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static explicit operator U32x2(F64x2 v) { return new U32x2(v); }


        /// <summary>Returns the result of a componentwise multiplication operation on two U32x2 vectors.</summary>
        /// <param name="lhs">Left hand side U32x2 to use to compute componentwise multiplication.</param>
        /// <param name="rhs">Right hand side U32x2 to use to compute componentwise multiplication.</param>
        /// <returns>U32x2 result of the componentwise multiplication.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2 operator * (U32x2 lhs, U32x2 rhs) { return new U32x2 (lhs.x * rhs.x, lhs.y * rhs.y); }

        /// <summary>Returns the result of a componentwise multiplication operation on a U32x2 vector and a uint value.</summary>
        /// <param name="lhs">Left hand side U32x2 to use to compute componentwise multiplication.</param>
        /// <param name="rhs">Right hand side uint to use to compute componentwise multiplication.</param>
        /// <returns>U32x2 result of the componentwise multiplication.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2 operator * (U32x2 lhs, uint rhs) { return new U32x2 (lhs.x * rhs, lhs.y * rhs); }

        /// <summary>Returns the result of a componentwise multiplication operation on a uint value and a U32x2 vector.</summary>
        /// <param name="lhs">Left hand side uint to use to compute componentwise multiplication.</param>
        /// <param name="rhs">Right hand side U32x2 to use to compute componentwise multiplication.</param>
        /// <returns>U32x2 result of the componentwise multiplication.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2 operator * (uint lhs, U32x2 rhs) { return new U32x2 (lhs * rhs.x, lhs * rhs.y); }


        /// <summary>Returns the result of a componentwise addition operation on two U32x2 vectors.</summary>
        /// <param name="lhs">Left hand side U32x2 to use to compute componentwise addition.</param>
        /// <param name="rhs">Right hand side U32x2 to use to compute componentwise addition.</param>
        /// <returns>U32x2 result of the componentwise addition.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2 operator + (U32x2 lhs, U32x2 rhs) { return new U32x2 (lhs.x + rhs.x, lhs.y + rhs.y); }

        /// <summary>Returns the result of a componentwise addition operation on a U32x2 vector and a uint value.</summary>
        /// <param name="lhs">Left hand side U32x2 to use to compute componentwise addition.</param>
        /// <param name="rhs">Right hand side uint to use to compute componentwise addition.</param>
        /// <returns>U32x2 result of the componentwise addition.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2 operator + (U32x2 lhs, uint rhs) { return new U32x2 (lhs.x + rhs, lhs.y + rhs); }

        /// <summary>Returns the result of a componentwise addition operation on a uint value and a U32x2 vector.</summary>
        /// <param name="lhs">Left hand side uint to use to compute componentwise addition.</param>
        /// <param name="rhs">Right hand side U32x2 to use to compute componentwise addition.</param>
        /// <returns>U32x2 result of the componentwise addition.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2 operator + (uint lhs, U32x2 rhs) { return new U32x2 (lhs + rhs.x, lhs + rhs.y); }


        /// <summary>Returns the result of a componentwise subtraction operation on two U32x2 vectors.</summary>
        /// <param name="lhs">Left hand side U32x2 to use to compute componentwise subtraction.</param>
        /// <param name="rhs">Right hand side U32x2 to use to compute componentwise subtraction.</param>
        /// <returns>U32x2 result of the componentwise subtraction.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2 operator - (U32x2 lhs, U32x2 rhs) { return new U32x2 (lhs.x - rhs.x, lhs.y - rhs.y); }

        /// <summary>Returns the result of a componentwise subtraction operation on a U32x2 vector and a uint value.</summary>
        /// <param name="lhs">Left hand side U32x2 to use to compute componentwise subtraction.</param>
        /// <param name="rhs">Right hand side uint to use to compute componentwise subtraction.</param>
        /// <returns>U32x2 result of the componentwise subtraction.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2 operator - (U32x2 lhs, uint rhs) { return new U32x2 (lhs.x - rhs, lhs.y - rhs); }

        /// <summary>Returns the result of a componentwise subtraction operation on a uint value and a U32x2 vector.</summary>
        /// <param name="lhs">Left hand side uint to use to compute componentwise subtraction.</param>
        /// <param name="rhs">Right hand side U32x2 to use to compute componentwise subtraction.</param>
        /// <returns>U32x2 result of the componentwise subtraction.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2 operator - (uint lhs, U32x2 rhs) { return new U32x2 (lhs - rhs.x, lhs - rhs.y); }


        /// <summary>Returns the result of a componentwise division operation on two U32x2 vectors.</summary>
        /// <param name="lhs">Left hand side U32x2 to use to compute componentwise division.</param>
        /// <param name="rhs">Right hand side U32x2 to use to compute componentwise division.</param>
        /// <returns>U32x2 result of the componentwise division.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2 operator / (U32x2 lhs, U32x2 rhs) { return new U32x2 (lhs.x / rhs.x, lhs.y / rhs.y); }

        /// <summary>Returns the result of a componentwise division operation on a U32x2 vector and a uint value.</summary>
        /// <param name="lhs">Left hand side U32x2 to use to compute componentwise division.</param>
        /// <param name="rhs">Right hand side uint to use to compute componentwise division.</param>
        /// <returns>U32x2 result of the componentwise division.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2 operator / (U32x2 lhs, uint rhs) { return new U32x2 (lhs.x / rhs, lhs.y / rhs); }

        /// <summary>Returns the result of a componentwise division operation on a uint value and a U32x2 vector.</summary>
        /// <param name="lhs">Left hand side uint to use to compute componentwise division.</param>
        /// <param name="rhs">Right hand side U32x2 to use to compute componentwise division.</param>
        /// <returns>U32x2 result of the componentwise division.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2 operator / (uint lhs, U32x2 rhs) { return new U32x2 (lhs / rhs.x, lhs / rhs.y); }


        /// <summary>Returns the result of a componentwise modulus operation on two U32x2 vectors.</summary>
        /// <param name="lhs">Left hand side U32x2 to use to compute componentwise modulus.</param>
        /// <param name="rhs">Right hand side U32x2 to use to compute componentwise modulus.</param>
        /// <returns>U32x2 result of the componentwise modulus.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2 operator % (U32x2 lhs, U32x2 rhs) { return new U32x2 (lhs.x % rhs.x, lhs.y % rhs.y); }

        /// <summary>Returns the result of a componentwise modulus operation on a U32x2 vector and a uint value.</summary>
        /// <param name="lhs">Left hand side U32x2 to use to compute componentwise modulus.</param>
        /// <param name="rhs">Right hand side uint to use to compute componentwise modulus.</param>
        /// <returns>U32x2 result of the componentwise modulus.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2 operator % (U32x2 lhs, uint rhs) { return new U32x2 (lhs.x % rhs, lhs.y % rhs); }

        /// <summary>Returns the result of a componentwise modulus operation on a uint value and a U32x2 vector.</summary>
        /// <param name="lhs">Left hand side uint to use to compute componentwise modulus.</param>
        /// <param name="rhs">Right hand side U32x2 to use to compute componentwise modulus.</param>
        /// <returns>U32x2 result of the componentwise modulus.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2 operator % (uint lhs, U32x2 rhs) { return new U32x2 (lhs % rhs.x, lhs % rhs.y); }


        /// <summary>Returns the result of a componentwise increment operation on a U32x2 vector.</summary>
        /// <param name="val">Value to use when computing the componentwise increment.</param>
        /// <returns>U32x2 result of the componentwise increment.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2 operator ++ (U32x2 val) { return new U32x2 (++val.x, ++val.y); }


        /// <summary>Returns the result of a componentwise decrement operation on a U32x2 vector.</summary>
        /// <param name="val">Value to use when computing the componentwise decrement.</param>
        /// <returns>U32x2 result of the componentwise decrement.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2 operator -- (U32x2 val) { return new U32x2 (--val.x, --val.y); }


        /// <summary>Returns the result of a componentwise less than operation on two U32x2 vectors.</summary>
        /// <param name="lhs">Left hand side U32x2 to use to compute componentwise less than.</param>
        /// <param name="rhs">Right hand side U32x2 to use to compute componentwise less than.</param>
        /// <returns>Boolx2 result of the componentwise less than.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Boolx2 operator < (U32x2 lhs, U32x2 rhs) { return new Boolx2 (lhs.x < rhs.x, lhs.y < rhs.y); }

        /// <summary>Returns the result of a componentwise less than operation on a U32x2 vector and a uint value.</summary>
        /// <param name="lhs">Left hand side U32x2 to use to compute componentwise less than.</param>
        /// <param name="rhs">Right hand side uint to use to compute componentwise less than.</param>
        /// <returns>Boolx2 result of the componentwise less than.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Boolx2 operator < (U32x2 lhs, uint rhs) { return new Boolx2 (lhs.x < rhs, lhs.y < rhs); }

        /// <summary>Returns the result of a componentwise less than operation on a uint value and a U32x2 vector.</summary>
        /// <param name="lhs">Left hand side uint to use to compute componentwise less than.</param>
        /// <param name="rhs">Right hand side U32x2 to use to compute componentwise less than.</param>
        /// <returns>Boolx2 result of the componentwise less than.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Boolx2 operator < (uint lhs, U32x2 rhs) { return new Boolx2 (lhs < rhs.x, lhs < rhs.y); }


        /// <summary>Returns the result of a componentwise less or equal operation on two U32x2 vectors.</summary>
        /// <param name="lhs">Left hand side U32x2 to use to compute componentwise less or equal.</param>
        /// <param name="rhs">Right hand side U32x2 to use to compute componentwise less or equal.</param>
        /// <returns>Boolx2 result of the componentwise less or equal.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Boolx2 operator <= (U32x2 lhs, U32x2 rhs) { return new Boolx2 (lhs.x <= rhs.x, lhs.y <= rhs.y); }

        /// <summary>Returns the result of a componentwise less or equal operation on a U32x2 vector and a uint value.</summary>
        /// <param name="lhs">Left hand side U32x2 to use to compute componentwise less or equal.</param>
        /// <param name="rhs">Right hand side uint to use to compute componentwise less or equal.</param>
        /// <returns>Boolx2 result of the componentwise less or equal.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Boolx2 operator <= (U32x2 lhs, uint rhs) { return new Boolx2 (lhs.x <= rhs, lhs.y <= rhs); }

        /// <summary>Returns the result of a componentwise less or equal operation on a uint value and a U32x2 vector.</summary>
        /// <param name="lhs">Left hand side uint to use to compute componentwise less or equal.</param>
        /// <param name="rhs">Right hand side U32x2 to use to compute componentwise less or equal.</param>
        /// <returns>Boolx2 result of the componentwise less or equal.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Boolx2 operator <= (uint lhs, U32x2 rhs) { return new Boolx2 (lhs <= rhs.x, lhs <= rhs.y); }


        /// <summary>Returns the result of a componentwise greater than operation on two U32x2 vectors.</summary>
        /// <param name="lhs">Left hand side U32x2 to use to compute componentwise greater than.</param>
        /// <param name="rhs">Right hand side U32x2 to use to compute componentwise greater than.</param>
        /// <returns>Boolx2 result of the componentwise greater than.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Boolx2 operator > (U32x2 lhs, U32x2 rhs) { return new Boolx2 (lhs.x > rhs.x, lhs.y > rhs.y); }

        /// <summary>Returns the result of a componentwise greater than operation on a U32x2 vector and a uint value.</summary>
        /// <param name="lhs">Left hand side U32x2 to use to compute componentwise greater than.</param>
        /// <param name="rhs">Right hand side uint to use to compute componentwise greater than.</param>
        /// <returns>Boolx2 result of the componentwise greater than.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Boolx2 operator > (U32x2 lhs, uint rhs) { return new Boolx2 (lhs.x > rhs, lhs.y > rhs); }

        /// <summary>Returns the result of a componentwise greater than operation on a uint value and a U32x2 vector.</summary>
        /// <param name="lhs">Left hand side uint to use to compute componentwise greater than.</param>
        /// <param name="rhs">Right hand side U32x2 to use to compute componentwise greater than.</param>
        /// <returns>Boolx2 result of the componentwise greater than.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Boolx2 operator > (uint lhs, U32x2 rhs) { return new Boolx2 (lhs > rhs.x, lhs > rhs.y); }


        /// <summary>Returns the result of a componentwise greater or equal operation on two U32x2 vectors.</summary>
        /// <param name="lhs">Left hand side U32x2 to use to compute componentwise greater or equal.</param>
        /// <param name="rhs">Right hand side U32x2 to use to compute componentwise greater or equal.</param>
        /// <returns>Boolx2 result of the componentwise greater or equal.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Boolx2 operator >= (U32x2 lhs, U32x2 rhs) { return new Boolx2 (lhs.x >= rhs.x, lhs.y >= rhs.y); }

        /// <summary>Returns the result of a componentwise greater or equal operation on a U32x2 vector and a uint value.</summary>
        /// <param name="lhs">Left hand side U32x2 to use to compute componentwise greater or equal.</param>
        /// <param name="rhs">Right hand side uint to use to compute componentwise greater or equal.</param>
        /// <returns>Boolx2 result of the componentwise greater or equal.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Boolx2 operator >= (U32x2 lhs, uint rhs) { return new Boolx2 (lhs.x >= rhs, lhs.y >= rhs); }

        /// <summary>Returns the result of a componentwise greater or equal operation on a uint value and a U32x2 vector.</summary>
        /// <param name="lhs">Left hand side uint to use to compute componentwise greater or equal.</param>
        /// <param name="rhs">Right hand side U32x2 to use to compute componentwise greater or equal.</param>
        /// <returns>Boolx2 result of the componentwise greater or equal.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Boolx2 operator >= (uint lhs, U32x2 rhs) { return new Boolx2 (lhs >= rhs.x, lhs >= rhs.y); }


        /// <summary>Returns the result of a componentwise unary minus operation on a U32x2 vector.</summary>
        /// <param name="val">Value to use when computing the componentwise unary minus.</param>
        /// <returns>U32x2 result of the componentwise unary minus.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2 operator - (U32x2 val) { return new U32x2 ((uint)-val.x, (uint)-val.y); }


        /// <summary>Returns the result of a componentwise unary plus operation on a U32x2 vector.</summary>
        /// <param name="val">Value to use when computing the componentwise unary plus.</param>
        /// <returns>U32x2 result of the componentwise unary plus.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2 operator + (U32x2 val) { return new U32x2 (+val.x, +val.y); }


        /// <summary>Returns the result of a componentwise left shift operation on a U32x2 vector by a number of bits specified by a single int.</summary>
        /// <param name="x">The vector to left shift.</param>
        /// <param name="n">The number of bits to left shift.</param>
        /// <returns>The result of the componentwise left shift.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2 operator << (U32x2 x, int n) { return new U32x2 (x.x << n, x.y << n); }

        /// <summary>Returns the result of a componentwise right shift operation on a U32x2 vector by a number of bits specified by a single int.</summary>
        /// <param name="x">The vector to right shift.</param>
        /// <param name="n">The number of bits to right shift.</param>
        /// <returns>The result of the componentwise right shift.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2 operator >> (U32x2 x, int n) { return new U32x2 (x.x >> n, x.y >> n); }

        /// <summary>Returns the result of a componentwise equality operation on two U32x2 vectors.</summary>
        /// <param name="lhs">Left hand side U32x2 to use to compute componentwise equality.</param>
        /// <param name="rhs">Right hand side U32x2 to use to compute componentwise equality.</param>
        /// <returns>Boolx2 result of the componentwise equality.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Boolx2 operator == (U32x2 lhs, U32x2 rhs) { return new Boolx2 (lhs.x == rhs.x, lhs.y == rhs.y); }

        /// <summary>Returns the result of a componentwise equality operation on a U32x2 vector and a uint value.</summary>
        /// <param name="lhs">Left hand side U32x2 to use to compute componentwise equality.</param>
        /// <param name="rhs">Right hand side uint to use to compute componentwise equality.</param>
        /// <returns>Boolx2 result of the componentwise equality.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Boolx2 operator == (U32x2 lhs, uint rhs) { return new Boolx2 (lhs.x == rhs, lhs.y == rhs); }

        /// <summary>Returns the result of a componentwise equality operation on a uint value and a U32x2 vector.</summary>
        /// <param name="lhs">Left hand side uint to use to compute componentwise equality.</param>
        /// <param name="rhs">Right hand side U32x2 to use to compute componentwise equality.</param>
        /// <returns>Boolx2 result of the componentwise equality.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Boolx2 operator == (uint lhs, U32x2 rhs) { return new Boolx2 (lhs == rhs.x, lhs == rhs.y); }


        /// <summary>Returns the result of a componentwise not equal operation on two U32x2 vectors.</summary>
        /// <param name="lhs">Left hand side U32x2 to use to compute componentwise not equal.</param>
        /// <param name="rhs">Right hand side U32x2 to use to compute componentwise not equal.</param>
        /// <returns>Boolx2 result of the componentwise not equal.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Boolx2 operator != (U32x2 lhs, U32x2 rhs) { return new Boolx2 (lhs.x != rhs.x, lhs.y != rhs.y); }

        /// <summary>Returns the result of a componentwise not equal operation on a U32x2 vector and a uint value.</summary>
        /// <param name="lhs">Left hand side U32x2 to use to compute componentwise not equal.</param>
        /// <param name="rhs">Right hand side uint to use to compute componentwise not equal.</param>
        /// <returns>Boolx2 result of the componentwise not equal.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Boolx2 operator != (U32x2 lhs, uint rhs) { return new Boolx2 (lhs.x != rhs, lhs.y != rhs); }

        /// <summary>Returns the result of a componentwise not equal operation on a uint value and a U32x2 vector.</summary>
        /// <param name="lhs">Left hand side uint to use to compute componentwise not equal.</param>
        /// <param name="rhs">Right hand side U32x2 to use to compute componentwise not equal.</param>
        /// <returns>Boolx2 result of the componentwise not equal.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Boolx2 operator != (uint lhs, U32x2 rhs) { return new Boolx2 (lhs != rhs.x, lhs != rhs.y); }


        /// <summary>Returns the result of a componentwise bitwise not operation on a U32x2 vector.</summary>
        /// <param name="val">Value to use when computing the componentwise bitwise not.</param>
        /// <returns>U32x2 result of the componentwise bitwise not.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2 operator ~ (U32x2 val) { return new U32x2 (~val.x, ~val.y); }


        /// <summary>Returns the result of a componentwise bitwise and operation on two U32x2 vectors.</summary>
        /// <param name="lhs">Left hand side U32x2 to use to compute componentwise bitwise and.</param>
        /// <param name="rhs">Right hand side U32x2 to use to compute componentwise bitwise and.</param>
        /// <returns>U32x2 result of the componentwise bitwise and.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2 operator & (U32x2 lhs, U32x2 rhs) { return new U32x2 (lhs.x & rhs.x, lhs.y & rhs.y); }

        /// <summary>Returns the result of a componentwise bitwise and operation on a U32x2 vector and a uint value.</summary>
        /// <param name="lhs">Left hand side U32x2 to use to compute componentwise bitwise and.</param>
        /// <param name="rhs">Right hand side uint to use to compute componentwise bitwise and.</param>
        /// <returns>U32x2 result of the componentwise bitwise and.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2 operator & (U32x2 lhs, uint rhs) { return new U32x2 (lhs.x & rhs, lhs.y & rhs); }

        /// <summary>Returns the result of a componentwise bitwise and operation on a uint value and a U32x2 vector.</summary>
        /// <param name="lhs">Left hand side uint to use to compute componentwise bitwise and.</param>
        /// <param name="rhs">Right hand side U32x2 to use to compute componentwise bitwise and.</param>
        /// <returns>U32x2 result of the componentwise bitwise and.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2 operator & (uint lhs, U32x2 rhs) { return new U32x2 (lhs & rhs.x, lhs & rhs.y); }


        /// <summary>Returns the result of a componentwise bitwise or operation on two U32x2 vectors.</summary>
        /// <param name="lhs">Left hand side U32x2 to use to compute componentwise bitwise or.</param>
        /// <param name="rhs">Right hand side U32x2 to use to compute componentwise bitwise or.</param>
        /// <returns>U32x2 result of the componentwise bitwise or.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2 operator | (U32x2 lhs, U32x2 rhs) { return new U32x2 (lhs.x | rhs.x, lhs.y | rhs.y); }

        /// <summary>Returns the result of a componentwise bitwise or operation on a U32x2 vector and a uint value.</summary>
        /// <param name="lhs">Left hand side U32x2 to use to compute componentwise bitwise or.</param>
        /// <param name="rhs">Right hand side uint to use to compute componentwise bitwise or.</param>
        /// <returns>U32x2 result of the componentwise bitwise or.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2 operator | (U32x2 lhs, uint rhs) { return new U32x2 (lhs.x | rhs, lhs.y | rhs); }

        /// <summary>Returns the result of a componentwise bitwise or operation on a uint value and a U32x2 vector.</summary>
        /// <param name="lhs">Left hand side uint to use to compute componentwise bitwise or.</param>
        /// <param name="rhs">Right hand side U32x2 to use to compute componentwise bitwise or.</param>
        /// <returns>U32x2 result of the componentwise bitwise or.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2 operator | (uint lhs, U32x2 rhs) { return new U32x2 (lhs | rhs.x, lhs | rhs.y); }


        /// <summary>Returns the result of a componentwise bitwise exclusive or operation on two U32x2 vectors.</summary>
        /// <param name="lhs">Left hand side U32x2 to use to compute componentwise bitwise exclusive or.</param>
        /// <param name="rhs">Right hand side U32x2 to use to compute componentwise bitwise exclusive or.</param>
        /// <returns>U32x2 result of the componentwise bitwise exclusive or.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2 operator ^ (U32x2 lhs, U32x2 rhs) { return new U32x2 (lhs.x ^ rhs.x, lhs.y ^ rhs.y); }

        /// <summary>Returns the result of a componentwise bitwise exclusive or operation on a U32x2 vector and a uint value.</summary>
        /// <param name="lhs">Left hand side U32x2 to use to compute componentwise bitwise exclusive or.</param>
        /// <param name="rhs">Right hand side uint to use to compute componentwise bitwise exclusive or.</param>
        /// <returns>U32x2 result of the componentwise bitwise exclusive or.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2 operator ^ (U32x2 lhs, uint rhs) { return new U32x2 (lhs.x ^ rhs, lhs.y ^ rhs); }

        /// <summary>Returns the result of a componentwise bitwise exclusive or operation on a uint value and a U32x2 vector.</summary>
        /// <param name="lhs">Left hand side uint to use to compute componentwise bitwise exclusive or.</param>
        /// <param name="rhs">Right hand side U32x2 to use to compute componentwise bitwise exclusive or.</param>
        /// <returns>U32x2 result of the componentwise bitwise exclusive or.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2 operator ^ (uint lhs, U32x2 rhs) { return new U32x2 (lhs ^ rhs.x, lhs ^ rhs.y); }




        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public U32x4 xxxx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new U32x4(x, x, x, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public U32x4 xxxy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new U32x4(x, x, x, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public U32x4 xxyx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new U32x4(x, x, y, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public U32x4 xxyy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new U32x4(x, x, y, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public U32x4 xyxx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new U32x4(x, y, x, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public U32x4 xyxy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new U32x4(x, y, x, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public U32x4 xyyx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new U32x4(x, y, y, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public U32x4 xyyy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new U32x4(x, y, y, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public U32x4 yxxx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new U32x4(y, x, x, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public U32x4 yxxy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new U32x4(y, x, x, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public U32x4 yxyx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new U32x4(y, x, y, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public U32x4 yxyy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new U32x4(y, x, y, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public U32x4 yyxx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new U32x4(y, y, x, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public U32x4 yyxy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new U32x4(y, y, x, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public U32x4 yyyx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new U32x4(y, y, y, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public U32x4 yyyy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new U32x4(y, y, y, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public U32x3 xxx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new U32x3(x, x, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public U32x3 xxy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new U32x3(x, x, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public U32x3 xyx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new U32x3(x, y, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public U32x3 xyy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new U32x3(x, y, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public U32x3 yxx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new U32x3(y, x, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public U32x3 yxy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new U32x3(y, x, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public U32x3 yyx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new U32x3(y, y, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public U32x3 yyy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new U32x3(y, y, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public U32x2 xx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new U32x2(x, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public U32x2 xy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new U32x2(x, y); }
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            set { x = value.x; y = value.y; }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public U32x2 yx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new U32x2(y, x); }
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            set { y = value.x; x = value.y; }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public U32x2 yy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new U32x2(y, y); }
        }



        /// <summary>Returns the uint element at a specified index.</summary>
        unsafe public uint this[int index]
        {
            get
            {
#if ENABLE_UNITY_COLLECTIONS_CHECKS
                if ((uint)index >= 2)
                    throw new System.ArgumentException("index must be between[0...1]");
#endif
                fixed (U32x2* array = &this) { return ((uint*)array)[index]; }
            }
            set
            {
#if ENABLE_UNITY_COLLECTIONS_CHECKS
                if ((uint)index >= 2)
                    throw new System.ArgumentException("index must be between[0...1]");
#endif
                fixed (uint* array = &x) { array[index] = value; }
            }
        }

        /// <summary>Returns true if the U32x2 is equal to a given U32x2, false otherwise.</summary>
        /// <param name="rhs">Right hand side argument to compare equality with.</param>
        /// <returns>The result of the equality comparison.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public bool Equals(U32x2 rhs) { return x == rhs.x && y == rhs.y; }

        /// <summary>Returns true if the U32x2 is equal to a given U32x2, false otherwise.</summary>
        /// <param name="o">Right hand side argument to compare equality with.</param>
        /// <returns>The result of the equality comparison.</returns>
        public override bool Equals(object o) { return o is U32x2 converted && Equals(converted); }


        /// <summary>Returns a hash code for the U32x2.</summary>
        /// <returns>The computed hash code.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public override int GetHashCode() { return (int)Maths.hash(this); }


        /// <summary>Returns a string representation of the U32x2.</summary>
        /// <returns>String representation of the value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public override string ToString()
        {
            return string.Format("U32x2({0}, {1})", x, y);
        }

        /// <summary>Returns a string representation of the U32x2 using a specified format and culture-specific format information.</summary>
        /// <param name="format">Format string to use during string formatting.</param>
        /// <param name="formatProvider">Format provider to use during string formatting.</param>
        /// <returns>String representation of the value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public string ToString(string format, IFormatProvider formatProvider)
        {
            return string.Format("U32x2({0}, {1})", x.ToString(format, formatProvider), y.ToString(format, formatProvider));
        }

        internal sealed class DebuggerProxy
        {
            public uint x;
            public uint y;
            public DebuggerProxy(U32x2 v)
            {
                x = v.x;
                y = v.y;
            }
        }

    }

    public static partial class Maths
    {
        /*
        /// <summary>Returns a U32x2 vector constructed from two uint values.</summary>
        /// <param name="x">The constructed vector's x component will be set to this value.</param>
        /// <param name="y">The constructed vector's y component will be set to this value.</param>
        /// <returns>U32x2 constructed from arguments.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2 new U32x2(uint x, uint y) { return new U32x2(x, y); }

        /// <summary>Returns a U32x2 vector constructed from a U32x2 vector.</summary>
        /// <param name="xy">The constructed vector's xy components will be set to this value.</param>
        /// <returns>U32x2 constructed from arguments.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2 new U32x2(U32x2 xy) { return new U32x2(xy); }

        /// <summary>Returns a U32x2 vector constructed from a single uint value by assigning it to every component.</summary>
        /// <param name="v">uint to convert to U32x2</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2 new U32x2(uint v) { return new U32x2(v); }

        /// <summary>Returns a U32x2 vector constructed from a single bool value by converting it to uint and assigning it to every component.</summary>
        /// <param name="v">bool to convert to U32x2</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2 new U32x2(bool v) { return new U32x2(v); }

        /// <summary>Return a U32x2 vector constructed from a Boolx2 vector by componentwise conversion.</summary>
        /// <param name="v">Boolx2 to convert to U32x2</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2 new U32x2(Boolx2 v) { return new U32x2(v); }

        /// <summary>Returns a U32x2 vector constructed from a single int value by converting it to uint and assigning it to every component.</summary>
        /// <param name="v">int to convert to U32x2</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2 new U32x2(int v) { return new U32x2(v); }

        /// <summary>Return a U32x2 vector constructed from a I32x2 vector by componentwise conversion.</summary>
        /// <param name="v">I32x2 to convert to U32x2</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2 new U32x2(I32x2 v) { return new U32x2(v); }

        /// <summary>Returns a U32x2 vector constructed from a single float value by converting it to uint and assigning it to every component.</summary>
        /// <param name="v">float to convert to U32x2</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2 new U32x2(float v) { return new U32x2(v); }

        /// <summary>Return a U32x2 vector constructed from a F32x2 vector by componentwise conversion.</summary>
        /// <param name="v">F32x2 to convert to U32x2</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2 new U32x2(F32x2 v) { return new U32x2(v); }

        /// <summary>Returns a U32x2 vector constructed from a single double value by converting it to uint and assigning it to every component.</summary>
        /// <param name="v">double to convert to U32x2</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2 new U32x2(double v) { return new U32x2(v); }

        /// <summary>Return a U32x2 vector constructed from a F64x2 vector by componentwise conversion.</summary>
        /// <param name="v">F64x2 to convert to U32x2</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2 new U32x2(F64x2 v) { return new U32x2(v); }
        */

        /// <summary>Returns a uint hash code of a U32x2 vector.</summary>
        /// <param name="v">Vector value to hash.</param>
        /// <returns>uint hash of the argument.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static uint hash(U32x2 v)
        {
            return csum(v * new U32x2(0x4473BBB1u, 0xCBA11D5Fu)) + 0x685835CFu;
        }

        /// <summary>
        /// Returns a U32x2 vector hash code of a U32x2 vector.
        /// When multiple elements are to be hashes together, it can more efficient to calculate and combine wide hash
        /// that are only reduced to a narrow uint hash at the very end instead of at every step.
        /// </summary>
        /// <param name="v">Vector value to hash.</param>
        /// <returns>U32x2 hash of the argument.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2 hashwide(U32x2 v)
        {
            return (v * new U32x2(0xC3D32AE1u, 0xB966942Fu)) + 0xFE9856B3u;
        }

        /// <summary>Returns the result of specified shuffling of the components from two U32x2 vectors into a uint value.</summary>
        /// <param name="left">U32x2 to use as the left argument of the shuffle operation.</param>
        /// <param name="right">U32x2 to use as the right argument of the shuffle operation.</param>
        /// <param name="x">The ShuffleComponent to use when setting the resulting uint.</param>
        /// <returns>uint result of the shuffle operation.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static uint shuffle(U32x2 left, U32x2 right, ShuffleComponent x)
        {
            return select_shuffle_component(left, right, x);
        }

        /// <summary>Returns the result of specified shuffling of the components from two U32x2 vectors into a U32x2 vector.</summary>
        /// <param name="left">U32x2 to use as the left argument of the shuffle operation.</param>
        /// <param name="right">U32x2 to use as the right argument of the shuffle operation.</param>
        /// <param name="x">The ShuffleComponent to use when setting the resulting U32x2 x component.</param>
        /// <param name="y">The ShuffleComponent to use when setting the resulting U32x2 y component.</param>
        /// <returns>U32x2 result of the shuffle operation.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2 shuffle(U32x2 left, U32x2 right, ShuffleComponent x, ShuffleComponent y)
        {
            return new U32x2(
                select_shuffle_component(left, right, x),
                select_shuffle_component(left, right, y));
        }

        /// <summary>Returns the result of specified shuffling of the components from two U32x2 vectors into a U32x3 vector.</summary>
        /// <param name="left">U32x2 to use as the left argument of the shuffle operation.</param>
        /// <param name="right">U32x2 to use as the right argument of the shuffle operation.</param>
        /// <param name="x">The ShuffleComponent to use when setting the resulting U32x3 x component.</param>
        /// <param name="y">The ShuffleComponent to use when setting the resulting U32x3 y component.</param>
        /// <param name="z">The ShuffleComponent to use when setting the resulting U32x3 z component.</param>
        /// <returns>U32x3 result of the shuffle operation.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x3 shuffle(U32x2 left, U32x2 right, ShuffleComponent x, ShuffleComponent y, ShuffleComponent z)
        {
            return new U32x3(
                select_shuffle_component(left, right, x),
                select_shuffle_component(left, right, y),
                select_shuffle_component(left, right, z));
        }

        /// <summary>Returns the result of specified shuffling of the components from two U32x2 vectors into a U32x4 vector.</summary>
        /// <param name="left">U32x2 to use as the left argument of the shuffle operation.</param>
        /// <param name="right">U32x2 to use as the right argument of the shuffle operation.</param>
        /// <param name="x">The ShuffleComponent to use when setting the resulting U32x4 x component.</param>
        /// <param name="y">The ShuffleComponent to use when setting the resulting U32x4 y component.</param>
        /// <param name="z">The ShuffleComponent to use when setting the resulting U32x4 z component.</param>
        /// <param name="w">The ShuffleComponent to use when setting the resulting U32x4 w component.</param>
        /// <returns>U32x4 result of the shuffle operation.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x4 shuffle(U32x2 left, U32x2 right, ShuffleComponent x, ShuffleComponent y, ShuffleComponent z, ShuffleComponent w)
        {
            return new U32x4(
                select_shuffle_component(left, right, x),
                select_shuffle_component(left, right, y),
                select_shuffle_component(left, right, z),
                select_shuffle_component(left, right, w));
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal static uint select_shuffle_component(U32x2 a, U32x2 b, ShuffleComponent component)
        {
            switch(component)
            {
                case ShuffleComponent.LeftX:
                    return a.x;
                case ShuffleComponent.LeftY:
                    return a.y;
                case ShuffleComponent.RightX:
                    return b.x;
                case ShuffleComponent.RightY:
                    return b.y;
                default:
                    throw new System.ArgumentException("Invalid shuffle component: " + component);
            }
        }

    }
}
