//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Runtime.CompilerServices;
using Unity.IL2CPP.CompilerServices;

#pragma warning disable 0660, 0661

namespace CGTK.Utilities.BetterMath
{
    /// <summary>A 2x3 matrix of uints.</summary>
    [System.Serializable]
    [Il2CppEagerStaticClassConstruction]
    public partial struct U32x2x3 : System.IEquatable<U32x2x3>, IFormattable
    {
        /// <summary>Column 0 of the matrix.</summary>
        public U32x2 c0;
        /// <summary>Column 1 of the matrix.</summary>
        public U32x2 c1;
        /// <summary>Column 2 of the matrix.</summary>
        public U32x2 c2;

        /// <summary>U32x2x3 zero value.</summary>
        public static readonly U32x2x3 zero;

        /// <summary>Constructs a U32x2x3 matrix from three U32x2 vectors.</summary>
        /// <param name="c0">The matrix column c0 will be set to this value.</param>
        /// <param name="c1">The matrix column c1 will be set to this value.</param>
        /// <param name="c2">The matrix column c2 will be set to this value.</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public U32x2x3(U32x2 c0, U32x2 c1, U32x2 c2)
        {
            this.c0 = c0;
            this.c1 = c1;
            this.c2 = c2;
        }

        /// <summary>Constructs a U32x2x3 matrix from 6 uint values given in row-major order.</summary>
        /// <param name="m00">The matrix at row 0, column 0 will be set to this value.</param>
        /// <param name="m01">The matrix at row 0, column 1 will be set to this value.</param>
        /// <param name="m02">The matrix at row 0, column 2 will be set to this value.</param>
        /// <param name="m10">The matrix at row 1, column 0 will be set to this value.</param>
        /// <param name="m11">The matrix at row 1, column 1 will be set to this value.</param>
        /// <param name="m12">The matrix at row 1, column 2 will be set to this value.</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public U32x2x3(uint m00, uint m01, uint m02,
                       uint m10, uint m11, uint m12)
        {
            this.c0 = new U32x2(m00, m10);
            this.c1 = new U32x2(m01, m11);
            this.c2 = new U32x2(m02, m12);
        }

        /// <summary>Constructs a U32x2x3 matrix from a single uint value by assigning it to every component.</summary>
        /// <param name="v">uint to convert to U32x2x3</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public U32x2x3(uint v)
        {
            this.c0 = v;
            this.c1 = v;
            this.c2 = v;
        }

        /// <summary>Constructs a U32x2x3 matrix from a single bool value by converting it to uint and assigning it to every component.</summary>
        /// <param name="v">bool to convert to U32x2x3</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public U32x2x3(bool v)
        {
            this.c0 = Maths.select(new U32x2(0u), new U32x2(1u), v);
            this.c1 = Maths.select(new U32x2(0u), new U32x2(1u), v);
            this.c2 = Maths.select(new U32x2(0u), new U32x2(1u), v);
        }

        /// <summary>Constructs a U32x2x3 matrix from a Boolx2x3 matrix by componentwise conversion.</summary>
        /// <param name="v">Boolx2x3 to convert to U32x2x3</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public U32x2x3(Boolx2x3 v)
        {
            this.c0 = Maths.select(new U32x2(0u), new U32x2(1u), v.c0);
            this.c1 = Maths.select(new U32x2(0u), new U32x2(1u), v.c1);
            this.c2 = Maths.select(new U32x2(0u), new U32x2(1u), v.c2);
        }

        /// <summary>Constructs a U32x2x3 matrix from a single int value by converting it to uint and assigning it to every component.</summary>
        /// <param name="v">int to convert to U32x2x3</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public U32x2x3(int v)
        {
            this.c0 = (U32x2)v;
            this.c1 = (U32x2)v;
            this.c2 = (U32x2)v;
        }

        /// <summary>Constructs a U32x2x3 matrix from a I32x2x3 matrix by componentwise conversion.</summary>
        /// <param name="v">I32x2x3 to convert to U32x2x3</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public U32x2x3(I32x2x3 v)
        {
            this.c0 = (U32x2)v.c0;
            this.c1 = (U32x2)v.c1;
            this.c2 = (U32x2)v.c2;
        }

        /// <summary>Constructs a U32x2x3 matrix from a single float value by converting it to uint and assigning it to every component.</summary>
        /// <param name="v">float to convert to U32x2x3</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public U32x2x3(float v)
        {
            this.c0 = (U32x2)v;
            this.c1 = (U32x2)v;
            this.c2 = (U32x2)v;
        }

        /// <summary>Constructs a U32x2x3 matrix from a F32x2x3 matrix by componentwise conversion.</summary>
        /// <param name="v">F32x2x3 to convert to U32x2x3</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public U32x2x3(F32x2x3 v)
        {
            this.c0 = (U32x2)v.c0;
            this.c1 = (U32x2)v.c1;
            this.c2 = (U32x2)v.c2;
        }

        /// <summary>Constructs a U32x2x3 matrix from a single double value by converting it to uint and assigning it to every component.</summary>
        /// <param name="v">double to convert to U32x2x3</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public U32x2x3(double v)
        {
            this.c0 = (U32x2)v;
            this.c1 = (U32x2)v;
            this.c2 = (U32x2)v;
        }

        /// <summary>Constructs a U32x2x3 matrix from a F64x2x3 matrix by componentwise conversion.</summary>
        /// <param name="v">F64x2x3 to convert to U32x2x3</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public U32x2x3(F64x2x3 v)
        {
            this.c0 = (U32x2)v.c0;
            this.c1 = (U32x2)v.c1;
            this.c2 = (U32x2)v.c2;
        }


        /// <summary>Implicitly converts a single uint value to a U32x2x3 matrix by assigning it to every component.</summary>
        /// <param name="v">uint to convert to U32x2x3</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator U32x2x3(uint v) { return new U32x2x3(v); }

        /// <summary>Explicitly converts a single bool value to a U32x2x3 matrix by converting it to uint and assigning it to every component.</summary>
        /// <param name="v">bool to convert to U32x2x3</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static explicit operator U32x2x3(bool v) { return new U32x2x3(v); }

        /// <summary>Explicitly converts a Boolx2x3 matrix to a U32x2x3 matrix by componentwise conversion.</summary>
        /// <param name="v">Boolx2x3 to convert to U32x2x3</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static explicit operator U32x2x3(Boolx2x3 v) { return new U32x2x3(v); }

        /// <summary>Explicitly converts a single int value to a U32x2x3 matrix by converting it to uint and assigning it to every component.</summary>
        /// <param name="v">int to convert to U32x2x3</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static explicit operator U32x2x3(int v) { return new U32x2x3(v); }

        /// <summary>Explicitly converts a I32x2x3 matrix to a U32x2x3 matrix by componentwise conversion.</summary>
        /// <param name="v">I32x2x3 to convert to U32x2x3</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static explicit operator U32x2x3(I32x2x3 v) { return new U32x2x3(v); }

        /// <summary>Explicitly converts a single float value to a U32x2x3 matrix by converting it to uint and assigning it to every component.</summary>
        /// <param name="v">float to convert to U32x2x3</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static explicit operator U32x2x3(float v) { return new U32x2x3(v); }

        /// <summary>Explicitly converts a F32x2x3 matrix to a U32x2x3 matrix by componentwise conversion.</summary>
        /// <param name="v">F32x2x3 to convert to U32x2x3</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static explicit operator U32x2x3(F32x2x3 v) { return new U32x2x3(v); }

        /// <summary>Explicitly converts a single double value to a U32x2x3 matrix by converting it to uint and assigning it to every component.</summary>
        /// <param name="v">double to convert to U32x2x3</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static explicit operator U32x2x3(double v) { return new U32x2x3(v); }

        /// <summary>Explicitly converts a F64x2x3 matrix to a U32x2x3 matrix by componentwise conversion.</summary>
        /// <param name="v">F64x2x3 to convert to U32x2x3</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static explicit operator U32x2x3(F64x2x3 v) { return new U32x2x3(v); }


        /// <summary>Returns the result of a componentwise multiplication operation on two U32x2x3 matrices.</summary>
        /// <param name="lhs">Left hand side U32x2x3 to use to compute componentwise multiplication.</param>
        /// <param name="rhs">Right hand side U32x2x3 to use to compute componentwise multiplication.</param>
        /// <returns>U32x2x3 result of the componentwise multiplication.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2x3 operator * (U32x2x3 lhs, U32x2x3 rhs) { return new U32x2x3 (lhs.c0 * rhs.c0, lhs.c1 * rhs.c1, lhs.c2 * rhs.c2); }

        /// <summary>Returns the result of a componentwise multiplication operation on a U32x2x3 matrix and a uint value.</summary>
        /// <param name="lhs">Left hand side U32x2x3 to use to compute componentwise multiplication.</param>
        /// <param name="rhs">Right hand side uint to use to compute componentwise multiplication.</param>
        /// <returns>U32x2x3 result of the componentwise multiplication.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2x3 operator * (U32x2x3 lhs, uint rhs) { return new U32x2x3 (lhs.c0 * rhs, lhs.c1 * rhs, lhs.c2 * rhs); }

        /// <summary>Returns the result of a componentwise multiplication operation on a uint value and a U32x2x3 matrix.</summary>
        /// <param name="lhs">Left hand side uint to use to compute componentwise multiplication.</param>
        /// <param name="rhs">Right hand side U32x2x3 to use to compute componentwise multiplication.</param>
        /// <returns>U32x2x3 result of the componentwise multiplication.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2x3 operator * (uint lhs, U32x2x3 rhs) { return new U32x2x3 (lhs * rhs.c0, lhs * rhs.c1, lhs * rhs.c2); }


        /// <summary>Returns the result of a componentwise addition operation on two U32x2x3 matrices.</summary>
        /// <param name="lhs">Left hand side U32x2x3 to use to compute componentwise addition.</param>
        /// <param name="rhs">Right hand side U32x2x3 to use to compute componentwise addition.</param>
        /// <returns>U32x2x3 result of the componentwise addition.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2x3 operator + (U32x2x3 lhs, U32x2x3 rhs) { return new U32x2x3 (lhs.c0 + rhs.c0, lhs.c1 + rhs.c1, lhs.c2 + rhs.c2); }

        /// <summary>Returns the result of a componentwise addition operation on a U32x2x3 matrix and a uint value.</summary>
        /// <param name="lhs">Left hand side U32x2x3 to use to compute componentwise addition.</param>
        /// <param name="rhs">Right hand side uint to use to compute componentwise addition.</param>
        /// <returns>U32x2x3 result of the componentwise addition.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2x3 operator + (U32x2x3 lhs, uint rhs) { return new U32x2x3 (lhs.c0 + rhs, lhs.c1 + rhs, lhs.c2 + rhs); }

        /// <summary>Returns the result of a componentwise addition operation on a uint value and a U32x2x3 matrix.</summary>
        /// <param name="lhs">Left hand side uint to use to compute componentwise addition.</param>
        /// <param name="rhs">Right hand side U32x2x3 to use to compute componentwise addition.</param>
        /// <returns>U32x2x3 result of the componentwise addition.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2x3 operator + (uint lhs, U32x2x3 rhs) { return new U32x2x3 (lhs + rhs.c0, lhs + rhs.c1, lhs + rhs.c2); }


        /// <summary>Returns the result of a componentwise subtraction operation on two U32x2x3 matrices.</summary>
        /// <param name="lhs">Left hand side U32x2x3 to use to compute componentwise subtraction.</param>
        /// <param name="rhs">Right hand side U32x2x3 to use to compute componentwise subtraction.</param>
        /// <returns>U32x2x3 result of the componentwise subtraction.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2x3 operator - (U32x2x3 lhs, U32x2x3 rhs) { return new U32x2x3 (lhs.c0 - rhs.c0, lhs.c1 - rhs.c1, lhs.c2 - rhs.c2); }

        /// <summary>Returns the result of a componentwise subtraction operation on a U32x2x3 matrix and a uint value.</summary>
        /// <param name="lhs">Left hand side U32x2x3 to use to compute componentwise subtraction.</param>
        /// <param name="rhs">Right hand side uint to use to compute componentwise subtraction.</param>
        /// <returns>U32x2x3 result of the componentwise subtraction.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2x3 operator - (U32x2x3 lhs, uint rhs) { return new U32x2x3 (lhs.c0 - rhs, lhs.c1 - rhs, lhs.c2 - rhs); }

        /// <summary>Returns the result of a componentwise subtraction operation on a uint value and a U32x2x3 matrix.</summary>
        /// <param name="lhs">Left hand side uint to use to compute componentwise subtraction.</param>
        /// <param name="rhs">Right hand side U32x2x3 to use to compute componentwise subtraction.</param>
        /// <returns>U32x2x3 result of the componentwise subtraction.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2x3 operator - (uint lhs, U32x2x3 rhs) { return new U32x2x3 (lhs - rhs.c0, lhs - rhs.c1, lhs - rhs.c2); }


        /// <summary>Returns the result of a componentwise division operation on two U32x2x3 matrices.</summary>
        /// <param name="lhs">Left hand side U32x2x3 to use to compute componentwise division.</param>
        /// <param name="rhs">Right hand side U32x2x3 to use to compute componentwise division.</param>
        /// <returns>U32x2x3 result of the componentwise division.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2x3 operator / (U32x2x3 lhs, U32x2x3 rhs) { return new U32x2x3 (lhs.c0 / rhs.c0, lhs.c1 / rhs.c1, lhs.c2 / rhs.c2); }

        /// <summary>Returns the result of a componentwise division operation on a U32x2x3 matrix and a uint value.</summary>
        /// <param name="lhs">Left hand side U32x2x3 to use to compute componentwise division.</param>
        /// <param name="rhs">Right hand side uint to use to compute componentwise division.</param>
        /// <returns>U32x2x3 result of the componentwise division.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2x3 operator / (U32x2x3 lhs, uint rhs) { return new U32x2x3 (lhs.c0 / rhs, lhs.c1 / rhs, lhs.c2 / rhs); }

        /// <summary>Returns the result of a componentwise division operation on a uint value and a U32x2x3 matrix.</summary>
        /// <param name="lhs">Left hand side uint to use to compute componentwise division.</param>
        /// <param name="rhs">Right hand side U32x2x3 to use to compute componentwise division.</param>
        /// <returns>U32x2x3 result of the componentwise division.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2x3 operator / (uint lhs, U32x2x3 rhs) { return new U32x2x3 (lhs / rhs.c0, lhs / rhs.c1, lhs / rhs.c2); }


        /// <summary>Returns the result of a componentwise modulus operation on two U32x2x3 matrices.</summary>
        /// <param name="lhs">Left hand side U32x2x3 to use to compute componentwise modulus.</param>
        /// <param name="rhs">Right hand side U32x2x3 to use to compute componentwise modulus.</param>
        /// <returns>U32x2x3 result of the componentwise modulus.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2x3 operator % (U32x2x3 lhs, U32x2x3 rhs) { return new U32x2x3 (lhs.c0 % rhs.c0, lhs.c1 % rhs.c1, lhs.c2 % rhs.c2); }

        /// <summary>Returns the result of a componentwise modulus operation on a U32x2x3 matrix and a uint value.</summary>
        /// <param name="lhs">Left hand side U32x2x3 to use to compute componentwise modulus.</param>
        /// <param name="rhs">Right hand side uint to use to compute componentwise modulus.</param>
        /// <returns>U32x2x3 result of the componentwise modulus.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2x3 operator % (U32x2x3 lhs, uint rhs) { return new U32x2x3 (lhs.c0 % rhs, lhs.c1 % rhs, lhs.c2 % rhs); }

        /// <summary>Returns the result of a componentwise modulus operation on a uint value and a U32x2x3 matrix.</summary>
        /// <param name="lhs">Left hand side uint to use to compute componentwise modulus.</param>
        /// <param name="rhs">Right hand side U32x2x3 to use to compute componentwise modulus.</param>
        /// <returns>U32x2x3 result of the componentwise modulus.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2x3 operator % (uint lhs, U32x2x3 rhs) { return new U32x2x3 (lhs % rhs.c0, lhs % rhs.c1, lhs % rhs.c2); }


        /// <summary>Returns the result of a componentwise increment operation on a U32x2x3 matrix.</summary>
        /// <param name="val">Value to use when computing the componentwise increment.</param>
        /// <returns>U32x2x3 result of the componentwise increment.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2x3 operator ++ (U32x2x3 val) { return new U32x2x3 (++val.c0, ++val.c1, ++val.c2); }


        /// <summary>Returns the result of a componentwise decrement operation on a U32x2x3 matrix.</summary>
        /// <param name="val">Value to use when computing the componentwise decrement.</param>
        /// <returns>U32x2x3 result of the componentwise decrement.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2x3 operator -- (U32x2x3 val) { return new U32x2x3 (--val.c0, --val.c1, --val.c2); }


        /// <summary>Returns the result of a componentwise less than operation on two U32x2x3 matrices.</summary>
        /// <param name="lhs">Left hand side U32x2x3 to use to compute componentwise less than.</param>
        /// <param name="rhs">Right hand side U32x2x3 to use to compute componentwise less than.</param>
        /// <returns>Boolx2x3 result of the componentwise less than.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Boolx2x3 operator < (U32x2x3 lhs, U32x2x3 rhs) { return new Boolx2x3 (lhs.c0 < rhs.c0, lhs.c1 < rhs.c1, lhs.c2 < rhs.c2); }

        /// <summary>Returns the result of a componentwise less than operation on a U32x2x3 matrix and a uint value.</summary>
        /// <param name="lhs">Left hand side U32x2x3 to use to compute componentwise less than.</param>
        /// <param name="rhs">Right hand side uint to use to compute componentwise less than.</param>
        /// <returns>Boolx2x3 result of the componentwise less than.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Boolx2x3 operator < (U32x2x3 lhs, uint rhs) { return new Boolx2x3 (lhs.c0 < rhs, lhs.c1 < rhs, lhs.c2 < rhs); }

        /// <summary>Returns the result of a componentwise less than operation on a uint value and a U32x2x3 matrix.</summary>
        /// <param name="lhs">Left hand side uint to use to compute componentwise less than.</param>
        /// <param name="rhs">Right hand side U32x2x3 to use to compute componentwise less than.</param>
        /// <returns>Boolx2x3 result of the componentwise less than.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Boolx2x3 operator < (uint lhs, U32x2x3 rhs) { return new Boolx2x3 (lhs < rhs.c0, lhs < rhs.c1, lhs < rhs.c2); }


        /// <summary>Returns the result of a componentwise less or equal operation on two U32x2x3 matrices.</summary>
        /// <param name="lhs">Left hand side U32x2x3 to use to compute componentwise less or equal.</param>
        /// <param name="rhs">Right hand side U32x2x3 to use to compute componentwise less or equal.</param>
        /// <returns>Boolx2x3 result of the componentwise less or equal.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Boolx2x3 operator <= (U32x2x3 lhs, U32x2x3 rhs) { return new Boolx2x3 (lhs.c0 <= rhs.c0, lhs.c1 <= rhs.c1, lhs.c2 <= rhs.c2); }

        /// <summary>Returns the result of a componentwise less or equal operation on a U32x2x3 matrix and a uint value.</summary>
        /// <param name="lhs">Left hand side U32x2x3 to use to compute componentwise less or equal.</param>
        /// <param name="rhs">Right hand side uint to use to compute componentwise less or equal.</param>
        /// <returns>Boolx2x3 result of the componentwise less or equal.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Boolx2x3 operator <= (U32x2x3 lhs, uint rhs) { return new Boolx2x3 (lhs.c0 <= rhs, lhs.c1 <= rhs, lhs.c2 <= rhs); }

        /// <summary>Returns the result of a componentwise less or equal operation on a uint value and a U32x2x3 matrix.</summary>
        /// <param name="lhs">Left hand side uint to use to compute componentwise less or equal.</param>
        /// <param name="rhs">Right hand side U32x2x3 to use to compute componentwise less or equal.</param>
        /// <returns>Boolx2x3 result of the componentwise less or equal.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Boolx2x3 operator <= (uint lhs, U32x2x3 rhs) { return new Boolx2x3 (lhs <= rhs.c0, lhs <= rhs.c1, lhs <= rhs.c2); }


        /// <summary>Returns the result of a componentwise greater than operation on two U32x2x3 matrices.</summary>
        /// <param name="lhs">Left hand side U32x2x3 to use to compute componentwise greater than.</param>
        /// <param name="rhs">Right hand side U32x2x3 to use to compute componentwise greater than.</param>
        /// <returns>Boolx2x3 result of the componentwise greater than.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Boolx2x3 operator > (U32x2x3 lhs, U32x2x3 rhs) { return new Boolx2x3 (lhs.c0 > rhs.c0, lhs.c1 > rhs.c1, lhs.c2 > rhs.c2); }

        /// <summary>Returns the result of a componentwise greater than operation on a U32x2x3 matrix and a uint value.</summary>
        /// <param name="lhs">Left hand side U32x2x3 to use to compute componentwise greater than.</param>
        /// <param name="rhs">Right hand side uint to use to compute componentwise greater than.</param>
        /// <returns>Boolx2x3 result of the componentwise greater than.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Boolx2x3 operator > (U32x2x3 lhs, uint rhs) { return new Boolx2x3 (lhs.c0 > rhs, lhs.c1 > rhs, lhs.c2 > rhs); }

        /// <summary>Returns the result of a componentwise greater than operation on a uint value and a U32x2x3 matrix.</summary>
        /// <param name="lhs">Left hand side uint to use to compute componentwise greater than.</param>
        /// <param name="rhs">Right hand side U32x2x3 to use to compute componentwise greater than.</param>
        /// <returns>Boolx2x3 result of the componentwise greater than.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Boolx2x3 operator > (uint lhs, U32x2x3 rhs) { return new Boolx2x3 (lhs > rhs.c0, lhs > rhs.c1, lhs > rhs.c2); }


        /// <summary>Returns the result of a componentwise greater or equal operation on two U32x2x3 matrices.</summary>
        /// <param name="lhs">Left hand side U32x2x3 to use to compute componentwise greater or equal.</param>
        /// <param name="rhs">Right hand side U32x2x3 to use to compute componentwise greater or equal.</param>
        /// <returns>Boolx2x3 result of the componentwise greater or equal.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Boolx2x3 operator >= (U32x2x3 lhs, U32x2x3 rhs) { return new Boolx2x3 (lhs.c0 >= rhs.c0, lhs.c1 >= rhs.c1, lhs.c2 >= rhs.c2); }

        /// <summary>Returns the result of a componentwise greater or equal operation on a U32x2x3 matrix and a uint value.</summary>
        /// <param name="lhs">Left hand side U32x2x3 to use to compute componentwise greater or equal.</param>
        /// <param name="rhs">Right hand side uint to use to compute componentwise greater or equal.</param>
        /// <returns>Boolx2x3 result of the componentwise greater or equal.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Boolx2x3 operator >= (U32x2x3 lhs, uint rhs) { return new Boolx2x3 (lhs.c0 >= rhs, lhs.c1 >= rhs, lhs.c2 >= rhs); }

        /// <summary>Returns the result of a componentwise greater or equal operation on a uint value and a U32x2x3 matrix.</summary>
        /// <param name="lhs">Left hand side uint to use to compute componentwise greater or equal.</param>
        /// <param name="rhs">Right hand side U32x2x3 to use to compute componentwise greater or equal.</param>
        /// <returns>Boolx2x3 result of the componentwise greater or equal.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Boolx2x3 operator >= (uint lhs, U32x2x3 rhs) { return new Boolx2x3 (lhs >= rhs.c0, lhs >= rhs.c1, lhs >= rhs.c2); }


        /// <summary>Returns the result of a componentwise unary minus operation on a U32x2x3 matrix.</summary>
        /// <param name="val">Value to use when computing the componentwise unary minus.</param>
        /// <returns>U32x2x3 result of the componentwise unary minus.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2x3 operator - (U32x2x3 val) { return new U32x2x3 (-val.c0, -val.c1, -val.c2); }


        /// <summary>Returns the result of a componentwise unary plus operation on a U32x2x3 matrix.</summary>
        /// <param name="val">Value to use when computing the componentwise unary plus.</param>
        /// <returns>U32x2x3 result of the componentwise unary plus.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2x3 operator + (U32x2x3 val) { return new U32x2x3 (+val.c0, +val.c1, +val.c2); }


        /// <summary>Returns the result of a componentwise left shift operation on a U32x2x3 matrix by a number of bits specified by a single int.</summary>
        /// <param name="x">The matrix to left shift.</param>
        /// <param name="n">The number of bits to left shift.</param>
        /// <returns>The result of the componentwise left shift.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2x3 operator << (U32x2x3 x, int n) { return new U32x2x3 (x.c0 << n, x.c1 << n, x.c2 << n); }

        /// <summary>Returns the result of a componentwise right shift operation on a U32x2x3 matrix by a number of bits specified by a single int.</summary>
        /// <param name="x">The matrix to right shift.</param>
        /// <param name="n">The number of bits to right shift.</param>
        /// <returns>The result of the componentwise right shift.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2x3 operator >> (U32x2x3 x, int n) { return new U32x2x3 (x.c0 >> n, x.c1 >> n, x.c2 >> n); }

        /// <summary>Returns the result of a componentwise equality operation on two U32x2x3 matrices.</summary>
        /// <param name="lhs">Left hand side U32x2x3 to use to compute componentwise equality.</param>
        /// <param name="rhs">Right hand side U32x2x3 to use to compute componentwise equality.</param>
        /// <returns>Boolx2x3 result of the componentwise equality.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Boolx2x3 operator == (U32x2x3 lhs, U32x2x3 rhs) { return new Boolx2x3 (lhs.c0 == rhs.c0, lhs.c1 == rhs.c1, lhs.c2 == rhs.c2); }

        /// <summary>Returns the result of a componentwise equality operation on a U32x2x3 matrix and a uint value.</summary>
        /// <param name="lhs">Left hand side U32x2x3 to use to compute componentwise equality.</param>
        /// <param name="rhs">Right hand side uint to use to compute componentwise equality.</param>
        /// <returns>Boolx2x3 result of the componentwise equality.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Boolx2x3 operator == (U32x2x3 lhs, uint rhs) { return new Boolx2x3 (lhs.c0 == rhs, lhs.c1 == rhs, lhs.c2 == rhs); }

        /// <summary>Returns the result of a componentwise equality operation on a uint value and a U32x2x3 matrix.</summary>
        /// <param name="lhs">Left hand side uint to use to compute componentwise equality.</param>
        /// <param name="rhs">Right hand side U32x2x3 to use to compute componentwise equality.</param>
        /// <returns>Boolx2x3 result of the componentwise equality.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Boolx2x3 operator == (uint lhs, U32x2x3 rhs) { return new Boolx2x3 (lhs == rhs.c0, lhs == rhs.c1, lhs == rhs.c2); }


        /// <summary>Returns the result of a componentwise not equal operation on two U32x2x3 matrices.</summary>
        /// <param name="lhs">Left hand side U32x2x3 to use to compute componentwise not equal.</param>
        /// <param name="rhs">Right hand side U32x2x3 to use to compute componentwise not equal.</param>
        /// <returns>Boolx2x3 result of the componentwise not equal.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Boolx2x3 operator != (U32x2x3 lhs, U32x2x3 rhs) { return new Boolx2x3 (lhs.c0 != rhs.c0, lhs.c1 != rhs.c1, lhs.c2 != rhs.c2); }

        /// <summary>Returns the result of a componentwise not equal operation on a U32x2x3 matrix and a uint value.</summary>
        /// <param name="lhs">Left hand side U32x2x3 to use to compute componentwise not equal.</param>
        /// <param name="rhs">Right hand side uint to use to compute componentwise not equal.</param>
        /// <returns>Boolx2x3 result of the componentwise not equal.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Boolx2x3 operator != (U32x2x3 lhs, uint rhs) { return new Boolx2x3 (lhs.c0 != rhs, lhs.c1 != rhs, lhs.c2 != rhs); }

        /// <summary>Returns the result of a componentwise not equal operation on a uint value and a U32x2x3 matrix.</summary>
        /// <param name="lhs">Left hand side uint to use to compute componentwise not equal.</param>
        /// <param name="rhs">Right hand side U32x2x3 to use to compute componentwise not equal.</param>
        /// <returns>Boolx2x3 result of the componentwise not equal.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Boolx2x3 operator != (uint lhs, U32x2x3 rhs) { return new Boolx2x3 (lhs != rhs.c0, lhs != rhs.c1, lhs != rhs.c2); }


        /// <summary>Returns the result of a componentwise bitwise not operation on a U32x2x3 matrix.</summary>
        /// <param name="val">Value to use when computing the componentwise bitwise not.</param>
        /// <returns>U32x2x3 result of the componentwise bitwise not.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2x3 operator ~ (U32x2x3 val) { return new U32x2x3 (~val.c0, ~val.c1, ~val.c2); }


        /// <summary>Returns the result of a componentwise bitwise and operation on two U32x2x3 matrices.</summary>
        /// <param name="lhs">Left hand side U32x2x3 to use to compute componentwise bitwise and.</param>
        /// <param name="rhs">Right hand side U32x2x3 to use to compute componentwise bitwise and.</param>
        /// <returns>U32x2x3 result of the componentwise bitwise and.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2x3 operator & (U32x2x3 lhs, U32x2x3 rhs) { return new U32x2x3 (lhs.c0 & rhs.c0, lhs.c1 & rhs.c1, lhs.c2 & rhs.c2); }

        /// <summary>Returns the result of a componentwise bitwise and operation on a U32x2x3 matrix and a uint value.</summary>
        /// <param name="lhs">Left hand side U32x2x3 to use to compute componentwise bitwise and.</param>
        /// <param name="rhs">Right hand side uint to use to compute componentwise bitwise and.</param>
        /// <returns>U32x2x3 result of the componentwise bitwise and.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2x3 operator & (U32x2x3 lhs, uint rhs) { return new U32x2x3 (lhs.c0 & rhs, lhs.c1 & rhs, lhs.c2 & rhs); }

        /// <summary>Returns the result of a componentwise bitwise and operation on a uint value and a U32x2x3 matrix.</summary>
        /// <param name="lhs">Left hand side uint to use to compute componentwise bitwise and.</param>
        /// <param name="rhs">Right hand side U32x2x3 to use to compute componentwise bitwise and.</param>
        /// <returns>U32x2x3 result of the componentwise bitwise and.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2x3 operator & (uint lhs, U32x2x3 rhs) { return new U32x2x3 (lhs & rhs.c0, lhs & rhs.c1, lhs & rhs.c2); }


        /// <summary>Returns the result of a componentwise bitwise or operation on two U32x2x3 matrices.</summary>
        /// <param name="lhs">Left hand side U32x2x3 to use to compute componentwise bitwise or.</param>
        /// <param name="rhs">Right hand side U32x2x3 to use to compute componentwise bitwise or.</param>
        /// <returns>U32x2x3 result of the componentwise bitwise or.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2x3 operator | (U32x2x3 lhs, U32x2x3 rhs) { return new U32x2x3 (lhs.c0 | rhs.c0, lhs.c1 | rhs.c1, lhs.c2 | rhs.c2); }

        /// <summary>Returns the result of a componentwise bitwise or operation on a U32x2x3 matrix and a uint value.</summary>
        /// <param name="lhs">Left hand side U32x2x3 to use to compute componentwise bitwise or.</param>
        /// <param name="rhs">Right hand side uint to use to compute componentwise bitwise or.</param>
        /// <returns>U32x2x3 result of the componentwise bitwise or.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2x3 operator | (U32x2x3 lhs, uint rhs) { return new U32x2x3 (lhs.c0 | rhs, lhs.c1 | rhs, lhs.c2 | rhs); }

        /// <summary>Returns the result of a componentwise bitwise or operation on a uint value and a U32x2x3 matrix.</summary>
        /// <param name="lhs">Left hand side uint to use to compute componentwise bitwise or.</param>
        /// <param name="rhs">Right hand side U32x2x3 to use to compute componentwise bitwise or.</param>
        /// <returns>U32x2x3 result of the componentwise bitwise or.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2x3 operator | (uint lhs, U32x2x3 rhs) { return new U32x2x3 (lhs | rhs.c0, lhs | rhs.c1, lhs | rhs.c2); }


        /// <summary>Returns the result of a componentwise bitwise exclusive or operation on two U32x2x3 matrices.</summary>
        /// <param name="lhs">Left hand side U32x2x3 to use to compute componentwise bitwise exclusive or.</param>
        /// <param name="rhs">Right hand side U32x2x3 to use to compute componentwise bitwise exclusive or.</param>
        /// <returns>U32x2x3 result of the componentwise bitwise exclusive or.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2x3 operator ^ (U32x2x3 lhs, U32x2x3 rhs) { return new U32x2x3 (lhs.c0 ^ rhs.c0, lhs.c1 ^ rhs.c1, lhs.c2 ^ rhs.c2); }

        /// <summary>Returns the result of a componentwise bitwise exclusive or operation on a U32x2x3 matrix and a uint value.</summary>
        /// <param name="lhs">Left hand side U32x2x3 to use to compute componentwise bitwise exclusive or.</param>
        /// <param name="rhs">Right hand side uint to use to compute componentwise bitwise exclusive or.</param>
        /// <returns>U32x2x3 result of the componentwise bitwise exclusive or.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2x3 operator ^ (U32x2x3 lhs, uint rhs) { return new U32x2x3 (lhs.c0 ^ rhs, lhs.c1 ^ rhs, lhs.c2 ^ rhs); }

        /// <summary>Returns the result of a componentwise bitwise exclusive or operation on a uint value and a U32x2x3 matrix.</summary>
        /// <param name="lhs">Left hand side uint to use to compute componentwise bitwise exclusive or.</param>
        /// <param name="rhs">Right hand side U32x2x3 to use to compute componentwise bitwise exclusive or.</param>
        /// <returns>U32x2x3 result of the componentwise bitwise exclusive or.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2x3 operator ^ (uint lhs, U32x2x3 rhs) { return new U32x2x3 (lhs ^ rhs.c0, lhs ^ rhs.c1, lhs ^ rhs.c2); }



        /// <summary>Returns the U32x2 element at a specified index.</summary>
        unsafe public ref U32x2 this[int index]
        {
            get
            {
#if ENABLE_UNITY_COLLECTIONS_CHECKS
                if ((uint)index >= 3)
                    throw new System.ArgumentException("index must be between[0...2]");
#endif
                fixed (U32x2x3* array = &this) { return ref ((U32x2*)array)[index]; }
            }
        }

        /// <summary>Returns true if the U32x2x3 is equal to a given U32x2x3, false otherwise.</summary>
        /// <param name="rhs">Right hand side argument to compare equality with.</param>
        /// <returns>The result of the equality comparison.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public bool Equals(U32x2x3 rhs) { return c0.Equals(rhs.c0) && c1.Equals(rhs.c1) && c2.Equals(rhs.c2); }

        /// <summary>Returns true if the U32x2x3 is equal to a given U32x2x3, false otherwise.</summary>
        /// <param name="o">Right hand side argument to compare equality with.</param>
        /// <returns>The result of the equality comparison.</returns>
        public override bool Equals(object o) { return o is U32x2x3 converted && Equals(converted); }


        /// <summary>Returns a hash code for the U32x2x3.</summary>
        /// <returns>The computed hash code.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public override int GetHashCode() { return (int)Maths.hash(this); }


        /// <summary>Returns a string representation of the U32x2x3.</summary>
        /// <returns>String representation of the value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public override string ToString()
        {
            return string.Format("U32x2x3({0}, {1}, {2},  {3}, {4}, {5})", c0.x, c1.x, c2.x, c0.y, c1.y, c2.y);
        }

        /// <summary>Returns a string representation of the U32x2x3 using a specified format and culture-specific format information.</summary>
        /// <param name="format">Format string to use during string formatting.</param>
        /// <param name="formatProvider">Format provider to use during string formatting.</param>
        /// <returns>String representation of the value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public string ToString(string format, IFormatProvider formatProvider)
        {
            return string.Format("U32x2x3({0}, {1}, {2},  {3}, {4}, {5})", c0.x.ToString(format, formatProvider), c1.x.ToString(format, formatProvider), c2.x.ToString(format, formatProvider), c0.y.ToString(format, formatProvider), c1.y.ToString(format, formatProvider), c2.y.ToString(format, formatProvider));
        }

    }

    public static partial class Maths
    {
        /*
        /// <summary>Returns a U32x2x3 matrix constructed from three U32x2 vectors.</summary>
        /// <param name="c0">The matrix column c0 will be set to this value.</param>
        /// <param name="c1">The matrix column c1 will be set to this value.</param>
        /// <param name="c2">The matrix column c2 will be set to this value.</param>
        /// <returns>U32x2x3 constructed from arguments.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2x3 uint2x3(U32x2 c0, U32x2 c1, U32x2 c2) { return new U32x2x3(c0, c1, c2); }

        /// <summary>Returns a U32x2x3 matrix constructed from from 6 uint values given in row-major order.</summary>
        /// <param name="m00">The matrix at row 0, column 0 will be set to this value.</param>
        /// <param name="m01">The matrix at row 0, column 1 will be set to this value.</param>
        /// <param name="m02">The matrix at row 0, column 2 will be set to this value.</param>
        /// <param name="m10">The matrix at row 1, column 0 will be set to this value.</param>
        /// <param name="m11">The matrix at row 1, column 1 will be set to this value.</param>
        /// <param name="m12">The matrix at row 1, column 2 will be set to this value.</param>
        /// <returns>U32x2x3 constructed from arguments.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2x3 uint2x3(uint m00, uint m01, uint m02,
                                      uint m10, uint m11, uint m12)
        {
            return new U32x2x3(m00, m01, m02,
                               m10, m11, m12);
        }

        /// <summary>Returns a U32x2x3 matrix constructed from a single uint value by assigning it to every component.</summary>
        /// <param name="v">uint to convert to U32x2x3</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2x3 uint2x3(uint v) { return new U32x2x3(v); }

        /// <summary>Returns a U32x2x3 matrix constructed from a single bool value by converting it to uint and assigning it to every component.</summary>
        /// <param name="v">bool to convert to U32x2x3</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2x3 uint2x3(bool v) { return new U32x2x3(v); }

        /// <summary>Return a U32x2x3 matrix constructed from a Boolx2x3 matrix by componentwise conversion.</summary>
        /// <param name="v">Boolx2x3 to convert to U32x2x3</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2x3 uint2x3(Boolx2x3 v) { return new U32x2x3(v); }

        /// <summary>Returns a U32x2x3 matrix constructed from a single int value by converting it to uint and assigning it to every component.</summary>
        /// <param name="v">int to convert to U32x2x3</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2x3 uint2x3(int v) { return new U32x2x3(v); }

        /// <summary>Return a U32x2x3 matrix constructed from a I32x2x3 matrix by componentwise conversion.</summary>
        /// <param name="v">I32x2x3 to convert to U32x2x3</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2x3 uint2x3(I32x2x3 v) { return new U32x2x3(v); }

        /// <summary>Returns a U32x2x3 matrix constructed from a single float value by converting it to uint and assigning it to every component.</summary>
        /// <param name="v">float to convert to U32x2x3</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2x3 uint2x3(float v) { return new U32x2x3(v); }

        /// <summary>Return a U32x2x3 matrix constructed from a F32x2x3 matrix by componentwise conversion.</summary>
        /// <param name="v">F32x2x3 to convert to U32x2x3</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2x3 uint2x3(F32x2x3 v) { return new U32x2x3(v); }

        /// <summary>Returns a U32x2x3 matrix constructed from a single double value by converting it to uint and assigning it to every component.</summary>
        /// <param name="v">double to convert to U32x2x3</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2x3 uint2x3(double v) { return new U32x2x3(v); }

        /// <summary>Return a U32x2x3 matrix constructed from a F64x2x3 matrix by componentwise conversion.</summary>
        /// <param name="v">F64x2x3 to convert to U32x2x3</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2x3 uint2x3(F64x2x3 v) { return new U32x2x3(v); }
        */

        /// <summary>Return the U32x3x2 transpose of a U32x2x3 matrix.</summary>
        /// <param name="v">Value to transpose.</param>
        /// <returns>Transposed value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x3x2 transpose(U32x2x3 v)
        {
            return new U32x3x2(
                v.c0.x, v.c0.y,
                v.c1.x, v.c1.y,
                v.c2.x, v.c2.y);
        }

        /// <summary>Returns a uint hash code of a U32x2x3 matrix.</summary>
        /// <param name="v">Matrix value to hash.</param>
        /// <returns>uint hash of the argument.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static uint hash(U32x2x3 v)
        {
            return csum(x:
                v.c0 * new U32x2(0xEF63C699u, 0x9001903Fu) +
                v.c1 * new U32x2(0xA895B9CDu, 0x9D23B201u) +
                v.c2 * new U32x2(0x4B01D3E1u, 0x7461CA0Du)) + 0x79725379u;
        }

        /// <summary>
        /// Returns a U32x2 vector hash code of a U32x2x3 matrix.
        /// When multiple elements are to be hashes together, it can more efficient to calculate and combine wide hash
        /// that are only reduced to a narrow uint hash at the very end instead of at every step.
        /// </summary>
        /// <param name="v">Matrix value to hash.</param>
        /// <returns>U32x2 hash of the argument.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static U32x2 hashwide(U32x2x3 v)
        {
            return (v.c0 * new U32x2(0xD6258E5Bu, 0xEE390C97u) +
                    v.c1 * new U32x2(0x9C8A2F05u, 0x4DDC6509u) +
                    v.c2 * new U32x2(0x7CF083CBu, 0x5C4D6CEDu)) + 0xF9137117u;
        }

    }
}
